export const dailyTipsContent = {
  en: {
    tips: [
      // --- ORIGINAL 30 TIPS (Basic to Advanced) ---
      "The ideal temperature for cream separation is 40-50°C. This ensures fat is liquid and viscosity is low for maximum efficiency.",
      "Homogenization of milk at 60-65°C and 2500 PSI (1st stage) followed by 500 PSI (2nd stage) prevents cream layer formation.",
      "The standard pasteurization (HTST) parameters for milk are heating to 72°C for 15 seconds. This kills all pathogenic bacteria.",
      "In paneer making, heating milk to 90°C denatures whey proteins, which then get entrapped in the casein coagulum, increasing the final yield.",
      "The characteristic flavor of yoghurt is primarily due to acetaldehyde, produced by the symbiotic action of Lactobacillus bulgaricus and Streptococcus thermophilus.",
      "A negative Alkaline Phosphatase (ALP) test is a confirmation of proper pasteurization in milk.",
      "The freezing point of milk is one of its most constant properties (-0.522 to -0.560°C). A reading closer to 0°C is a definite indication of added water.",
      "SNF stands for 'Solids-Not-Fat' and includes everything in milk except fat and water, i.e., proteins, lactose, and minerals.",
      "To increase SNF in milk for products like dahi or yoghurt, skimmed milk powder (SMP) is commonly added.",
      "The 'overrun' in ice cream refers to the percentage of air incorporated during freezing. A 100% overrun means the volume doubled.",
      "The characteristic 'buttery' flavor in cultured buttermilk and butter comes from diacetyl, a compound produced by specific starter bacteria.",
      "Ghee's characteristic nutty flavor develops during clarification when milk solids undergo Maillard reaction and caramelization at high temperatures (~110-114°C).",
      "The 'Cheddaring' process involves matting, piling, and turning curd blocks to develop the characteristic fibrous texture and acidity of Cheddar cheese.",
      "For Mozzarella cheese, the curd must be stretched in hot water (80-95°C) only after it reaches a specific pH of 5.2-5.4 to get its characteristic stretching property.",
      "In India, FSSAI legally distinguishes 'Ice Cream' (must use milk fat) from 'Frozen Dessert' (can use vegetable fat).",
      "The Brix value, measured by a refractometer, is used to determine the total soluble solids (mainly sugar) in sweetened condensed milk.",
      "Aflatoxin M1 is a harmful toxin that can be present in milk if the cattle consume contaminated feed. It is tested using HPLC.",
      "The Reichert-Meissl (RM) value of ghee is a measure of its purity and helps detect adulteration with vegetable oils.",
      "The purpose of an air curtain at a dairy plant's entrance is to create an invisible barrier that prevents flying insects from entering the processing area.",
      "Cleaning-In-Place (CIP) typically involves an alkali wash (to remove fat and protein) followed by an acid wash (to remove mineral scale like milk stone).",
      "Psychrotrophic bacteria in raw milk produce heat-stable lipases and proteases. Even if the bacteria die during pasteurization, these enzymes survive and cause bitterness or rancidity in shelf-stable milk later.",
      "In cheese production, Calcium Chloride (CaCl2) is often added to pasteurized milk to restore the calcium balance disrupted by heat, ensuring a firm curd set and reducing fines loss.",
      "The 'Salt Balance' (ratio of Ca/Mg to Phosphate/Citrate) is critical in UHT milk. If unbalanced, the milk will coagulate inside the heating tubes or gel during storage.",
      "Bacteriophages (viruses that kill bacteria) are the biggest secret threat in yoghurt plants. They can wipe out a culture tank in hours. 'Culture Rotation' is the only effective defense strategy.",
      "For High-Protein milks, Ultrafiltration (UF) is used instead of evaporation. UF membranes selectively remove water and lactose while retaining whey proteins and casein.",
      "In ice cream, 'Sandiness' is a defect caused by the crystallization of lactose. This happens if the MSNF (Milk Solids-Not-Fat) content is too high or storage temperature fluctuates (Heat Shock).",
      "Age Gelation is a major defect in UHT milk where it turns into a gel after 4-5 months. This is often caused by the reactivation of the natural enzyme 'Plasmin' inside the pack.",
      "Biofilms are bacterial layers that form inside pipes and are resistant to standard CIP. Regular use of oxidative sanitizers (like Peracetic Acid) is required to strip them away.",
      "The 'Kjeldahl Method' measures total nitrogen to estimate protein. However, adulterants like Melamine are nitrogen-rich and can trick this test, requiring specific LC-MS/MS testing for detection.",
      "Modified Atmosphere Packaging (MAP) for cheese involves replacing air with a mix of CO2 (to stop mold) and Nitrogen (to prevent package collapse), significantly extending shelf life.",

      // --- NEW ADDITIONS: PROCESSING ENGINEERING & CHEMISTRY ---
      "Regeneration Efficiency in a Plate Heat Exchanger (PHE) refers to how much heat from the outgoing hot milk is used to warm up the incoming cold milk, saving steam costs (usually 90-95%).",
      "Cavitation is a destructive phenomenon in homogenizers and pumps where vapor bubbles collapse, causing pitting on metal surfaces. It happens if the inlet pressure is too low.",
      "The Isoelectric Point of Casein is pH 4.6. At this pH, casein micelles lose their charge and precipitate, which is the fundamental principle behind making Dahi, Paneer, and Casein powder.",
      "Reverse Osmosis (RO) removes only water from milk, while Nanofiltration (NF) removes water and some monovalent ions (salt), making NF useful for demineralizing whey.",
      "In Spray Drying, the 'Outlet Temperature' controls the final moisture content of the powder. If it's too high, the powder becomes scorched (insoluble); if too low, the powder sticks to the chamber.",
      "WPNI (Whey Protein Nitrogen Index) classifies Skim Milk Powder. High Heat powder (WPNI < 1.5mg/g) is best for bakery/recombined milk, while Low Heat powder is best for making cheese.",
      "The 'Holding Tube' in a pasteurizer must have a specific slope (approx 2cm per meter) upwards to prevent air pockets that could insulate bacteria from heat.",
      "Steam Injection (Direct UHT) heats milk instantly but adds water, which must be removed by a 'Flash Vessel' (vacuum chamber) to restore the original solids content.",
      "Lecithin is a natural emulsifier found in the milk fat globule membrane (MFGM). In instant milk powder production, soya lecithin is sprayed (lecithination) to improve solubility in cold water.",
      "Over-homogenization can cause 'Cluster Formation' of fat globules, leading to high viscosity and poor creaming stability in coffee.",

      // --- NEW ADDITIONS: CHEESE & FERMENTATION SECRETS ---
      "Rennet (Chymosin) specifically cleaves the Kappa-Casein 'hairs' on the surface of casein micelles. Once these hairs are cut, the micelles stick together to form a curd.",
      "Late Blowing Defect in Gouda or Emmental cheese is caused by Clostridium tyrobutyricum spores (from silage). They produce hydrogen gas, cracking the cheese during ripening.",
      "Processed Cheese is made by melting natural cheese with 'Emulsifying Salts' (Citrates/Phosphates). These salts chelate calcium, converting the protein into a smooth, meltable structure.",
      "Syneresis (whey separation) in yoghurt happens if the incubation temperature is too high (>45°C) or if the gel is disturbed before cooling to 20°C.",
      "Propionibacterium shermanii is the specific bacteria added to Swiss Cheese to create the characteristic 'Eyes' (holes) by producing CO2 gas.",
      "Lipase enzymes are sometimes added deliberately to Italian cheeses (like Provolone) to create a spicy, piquant flavor by breaking down fats into free fatty acids.",
      "Annatto is the natural plant-based color (E160b) used to give Cheddar cheese its orange/yellow color. It is pH sensitive and turns pink at low pH.",
      "Phage-Robust Cultures are genetically selected bacterial strains that are resistant to specific bacteriophages, essential for large-scale reliable yoghurt production.",
      "The 'Stretch Test' in Mozzarella is basically testing the alignment of Casein fibers. If the pH is too low (<5.1), the curd breaks; if too high (>5.7), it stays rubbery and won't stretch.",
      "Camembert and Brie are 'Surface Ripened' cheeses. The white mold on the outside is Penicillium camemberti, which releases enzymes inward to soften the cheese core.",

      // --- NEW ADDITIONS: QUALITY & ADULTERATION (Detailed) ---
      "The Alcohol Test (using 68% or 70% ethanol) determines the heat stability of milk. If milk curdles with alcohol, it will likely coagulate in the UHT or sterilization process.",
      "Somatic Cell Count (SCC) indicates udder health. A count >400,000 cells/ml suggests Mastitis. High SCC milk has high enzymes and low casein, reducing cheese yield.",
      "Coliform count is a 'Hygiene Indicator'. Since coliforms are killed by pasteurization, their presence in finished milk proves Post-Pasteurization Contamination (PPC).",
      "Resazurin Test is a rapid platform test for bacterial load. High quality milk stays blue; poor quality milk turns pink or white quickly due to bacterial reduction.",
      "Antibiotic Residues (especially Beta-lactams like Penicillin) in milk prevent starter cultures from working. Even trace amounts can ruin an entire batch of yoghurt or cheese.",
      "Melamine was historically used as an adulterant because it contains 66% Nitrogen, tricking the Kjeldahl protein test. It causes kidney stones and is strictly monitored.",
      "Hydrogen Peroxide is an illegal preservative used to mask high bacterial counts. It destroys Vitamin C and Methionine in milk.",
      "Neutralizers (like Caustic Soda or Sodium Bicarbonate) are added to sour milk to correct the pH so it passes the platform test. This is detected using the Rosalic Acid test.",
      "Maltodextrin is a common adulterant in milk powder because it is cheap, soluble, and tasteless. It is detected using the Iodine test (turns reddish-brown, unlike starch which turns blue).",
      "Urea is naturally present in milk (~20-40 mg/dl), but high levels indicate adulteration to boost SNF values. The DMAB test identifies added urea.",

      // --- NEW ADDITIONS: ICE CREAM & FAT TECHNOLOGY ---
      "Stabilizers (like Guar Gum, Carrageenan) in ice cream function by binding water. This prevents free water from moving around and forming large, icy crystals during storage.",
      "Emulsifiers (like Mono- and Diglycerides) in ice cream destabilize the fat globules slightly, allowing them to clump around air bubbles, which supports the foam structure.",
      "The 'Hardening' step in ice cream (rapid freezing to -18°C or lower in a tunnel) must happen immediately after packaging to keep ice crystals microscopic.",
      "Iodine Value indicates the hardness of fat. Buffalo milk fat has a lower Iodine Value than Cow milk fat, making it harder and better for Ghee but riskier for butter spreadability.",
      "Polymorphism refers to fat crystal shapes. Butter requires Beta-prime crystals (fine needles). If temperature fluctuates, they shift to Beta crystals (large clumps), making butter grainy.",
      "Recrystallization is the biggest enemy of ice cream shelf life. It occurs when temperature fluctuates, causing small ice crystals to melt and join onto larger ones.",
      "Vegetable Fat in Frozen Desserts usually has a higher melting point than milk fat, which can leave a 'waxy' mouthfeel if not properly blended.",
      "Heat Shock in ice cream occurs when the product melts slightly during transport and refreezes, forming a layer of ice on top and a coarse texture inside.",
      "Supercooling is necessary for lactose crystallization in condensed milk. Seed lactose (fine micro-crystals) is added to force lactose to crystallize into small, undetectable sizes.",
      "Buttermilk powder is rich in Phospholipids (from the broken fat globule membranes), making it an excellent natural emulsifier for bakery applications.",

      // --- NEW ADDITIONS: PACKAGING & SHELF LIFE ---
      "ESL (Extended Shelf Life) milk lies between Pasteurization and UHT. It uses microfiltration or high-heat (125°C for 2s) to last 21-45 days under refrigeration.",
      "Oxygen Transmission Rate (OTR) of packaging film is critical for milk powder. If OTR is high, fat oxidation occurs, leading to rancidity within weeks.",
      "Aseptic Packaging (Tetra Pak) uses a laminate of Paper (structure), Polyethylene (sealing/barrier), and Aluminum Foil (light/oxygen barrier).",
      "Light Oxidation (Sunlight flavor) happens when milk is exposed to UV light (sun or supermarket LEDs). It degrades Methionine into methional, causing a 'burnt feather' or 'cabbage' smell.",
      "Headspace analysis in packaging checks for residual oxygen. For milk powder, residual oxygen must be <2% to guarantee a 1-2 year shelf life.",
      "Migration testing ensures that chemicals from the plastic packaging (ink or adhesives) do not leach into the fatty dairy product.",
      "Active Packaging involves adding oxygen scavengers (sachets or film coatings) inside cheese packs to actively absorb any oxygen trapped during sealing.",
      "Tamper-evident bands on milk bottles are shrinking due to heat. The tunnel temperature must be precise to shrink the band without warping the bottle neck.",
      "Glass bottles are chemically inert but allow light to pass through. Dark glass or UV-blocking sleeves are needed to prevent Vitamin B2 (Riboflavin) destruction.",
      "Edible coatings (made from casein or beeswax) are an emerging trend to package cheese portions without creating plastic waste.",

      // --- NEW ADDITIONS: WATER & EFFLUENT (Environment) ---
      "Dairy effluent typically has a high BOD (Biological Oxygen Demand) due to dissolved lactose and proteins. It cannot be dumped into rivers without aerobic/anaerobic treatment.",
      "Condensate Recovery: The water evaporated from milk during powder making (Cow Water) can be treated by RO and UV to be reused for boiler feed or plant cleaning.",
      "White Water is the mix of water and milk from the initial flush of pipes. It is often collected separately and used for pig feed or biogas generation rather than sent to the drain.",
      "Struvite formation (Magnesium Ammonium Phosphate) is a common problem in dairy biogas pipes, causing hard scale blockages due to the high mineral content of waste milk.",
      "Sludge from the dairy ETP (Effluent Treatment Plant) is rich in Nitrogen and Phosphorus, making it a valuable organic fertilizer for local farms."
    ]
  },
  hi: {
    tips: [
      // --- ORIGINAL 30 TIPS (Hinglish) ---
      "Cream separation ke liye ideal temperature 40-50°C hai. Isse fat liquid rehta hai aur viscosity kam hoti hai, jisse maximum efficiency milti hai.",
      "Doodh ka Homogenization 60-65°C aur 2500 PSI (1st stage) ke baad 500 PSI (2nd stage) par karne se cream layer nahi banti.",
      "Doodh ke liye standard Pasteurization (HTST) parameters 72°C par 15 seconds tak garam karna hai. Yeh sabhi harmful pathogenic bacteria ko khatam karta hai.",
      "Paneer banate waqt, doodh ko 90°C tak garam karne se whey proteins denature ho jate hain aur casein coagulum mein phans jate hain, jisse final yield badh jati hai.",
      "Yoghurt ka khaas flavor 'Acetaldehyde' ki wajah se hota hai, jo Lactobacillus bulgaricus aur Streptococcus thermophilus ke symbiotic action se banta hai.",
      "Negative Alkaline Phosphatase (ALP) test confirm karta hai ki doodh ka pasteurization sahi dhang se hua hai.",
      "Doodh ka freezing point sabse constant property hai (-0.522 se -0.560°C). Agar reading 0°C ke kareeb hai, toh iska matlab hai ki doodh mein pani milaya gaya hai.",
      "SNF ka matlab hai 'Solids-Not-Fat'. Ismein fat aur pani ko chhodkar doodh ke baaki sabhi elements jaise protein, lactose aur minerals aate hain.",
      "Dahi ya yoghurt jaise products mein SNF badhane ke liye aksar Skimmed Milk Powder (SMP) ka istemal kiya jata hai.",
      "Ice cream mein 'Overrun' ka matlab hai freezing ke dauran air ka percentage. 100% overrun ka matlab hai ki volume dugna ho gaya hai.",
      "Cultured buttermilk aur butter mein 'buttery' flavor Diacetyl ki wajah se aata hai, jo khaas starter bacteria produce karte hain.",
      "Ghee ka nutty flavor clarification ke dauran banta hai, jab milk solids high temperature (~110-114°C) par Maillard reaction aur caramelization se guzarte hain.",
      "'Cheddaring' process mein curd blocks ko matting, piling aur turn kiya jata hai taaki Cheddar cheese ka fibrous texture aur acidity develop ho sake.",
      "Mozzarella cheese ke liye, curd ko 80-95°C garam pani mein tabhi stretch karna chahiye jab uska pH 5.2-5.4 tak pahunch jaye. Tabhi stretchability aati hai.",
      "India mein, FSSAI legally 'Ice Cream' (milk fat user) aur 'Frozen Dessert' (vegetable fat user) ke beech clear farak rakhta hai.",
      "Brix value, jo refractometer se mapi jati hai, sweetened condensed milk mein total soluble solids (sugar) check karne ke liye use hoti hai.",
      "Aflatoxin M1 ek khatarnak toxin hai jo doodh mein aa sakta hai agar pashu ne contaminated feed khaya ho. Isse HPLC test se check kiya jata hai.",
      "Ghee ki purity aur vegetable oil ki milawat check karne ke liye Reichert-Meissl (RM) value ka use kiya jata hai.",
      "Dairy plant ke entrance par Air Curtain ka maqsad ek invisible barrier banana hai jo udne wale keedon (insects) ko processing area mein aane se rokta hai.",
      "Cleaning-In-Place (CIP) mein pehle alkali wash (fat/protein hatane ke liye) aur fir acid wash (milk stone hatane ke liye) kiya jata hai.",
      "Raw milk mein 'Psychrotrophic bacteria' hote hain jo heat-stable enzymes banate hain. Pasteurization mein bacteria mar jate hain, par ye enzymes bache rehte hain aur baad mein doodh ko kadwa (rancid) kar dete hain.",
      "Cheese production mein, pasteurized doodh mein Calcium Chloride (CaCl2) milaya jata hai taaki heat se bigda hua calcium balance theek ho sake aur curd firm bane.",
      "UHT doodh mein 'Salt Balance' (Calcium/Magnesium vs Phosphate/Citrate) critical hota hai. Agar balance bigad gaya, to doodh heating tubes ke andar hi jam jayega (coagulate ho jayega).",
      "Yoghurt plants mein 'Bacteriophages' (virus) sabse bada secret khatra hain. Ye culture tank ko ghanton mein khatam kar sakte hain. Isse bachne ka ek hi tareeka hai: 'Culture Rotation'.",
      "High-Protein milk banane ke liye evaporation nahi, balki 'Ultrafiltration (UF)' use hota hai. UF membranes pani aur lactose nikal deti hain par whey proteins ko bacha leti hain.",
      "Ice cream mein 'Sandiness' defect Lactose crystallization ki wajah se hota hai. Ye tab hota hai jab MSNF content bohot zyada ho ya storage temperature baar-baar badal raha ho (Heat Shock).",
      "UHT doodh mein 'Age Gelation' ek badi samasya hai jahan 4-5 mahine baad doodh gel ban jata hai. Ye aksar 'Plasmin' enzyme ke wapas active hone se hota hai.",
      "Pipes ke andar 'Biofilms' bacteria ki ek layer hoti hai jo normal CIP se nahi hat ti. Inhe hatane ke liye Peracetic Acid jaise strong oxidative sanitizers ki zaroorat padti hai.",
      "'Kjeldahl Method' protein mapne ke liye nitrogen check karta hai. Lekin Melamine jaise milawati tatv bhi nitrogen-rich hote hain, isliye pakadne ke liye advanced LC-MS/MS test chahiye hota hai.",
      "Cheese ki shelf life badhane ke liye 'Modified Atmosphere Packaging (MAP)' use hoti hai, jisme packet se hawa nikal kar CO2 (mold rokne ke liye) aur Nitrogen (packet shape ke liye) bhari jati hai.",

      // --- NEW ADDITIONS: PROCESSING ENGINEERING & CHEMISTRY (Hinglish) ---
      "PHE (Plate Heat Exchanger) mein 'Regeneration Efficiency' ka matlab hai ki garm doodh se thande doodh ko kitna garam kiya ja raha hai. Ye efficiency 90-95% honi chahiye taaki steam ka kharcha bache.",
      "Homogenizer mein 'Cavitation' ek destructive process hai. Agar inlet pressure kam ho, to vapor bubbles ban kar phat jate hain, jo metal pistons ko damage karte hain.",
      "Casein ka Isoelectric Point pH 4.6 hota hai. Is pH par doodh ka protein apna charge kho deta hai aur jam jata hai (precipitate). Yahi principle Dahi aur Paneer banane mein use hota hai.",
      "Reverse Osmosis (RO) sirf pani nikalta hai, jabki Nanofiltration (NF) pani ke saath-saath namak (salt) bhi nikalta hai. Isliye NF ka use whey ko demineralize karne ke liye hota hai.",
      "Spray Drying mein 'Outlet Temperature' powder ki moisture decide karta hai. Agar ye zyada hua to powder jal jayega (scorched), aur kam hua to powder chamber mein chipak jayega.",
      "WPNI (Whey Protein Nitrogen Index) se pata chalta hai ki powder kitna garam kiya gaya hai. Cheese ke liye 'Low Heat' powder aur bakery ke liye 'High Heat' powder best hota hai.",
      "Pasteurizer ke 'Holding Tube' mein hamesha upar ki taraf (upward) slope hona chahiye (approx 2cm/meter) taaki hawa ke bulbulon (air pockets) ko bacteria chupane ka mauka na mile.",
      "Direct UHT (Steam Injection) doodh ko turant garam karta hai par pani add kar deta hai. Is pani ko nikalne ke liye 'Flash Vessel' (vacuum chamber) ka use hota hai.",
      "Instant milk powder banane ke liye 'Lecithin' (soya se) spray kiya jata hai. Ye powder ko thande pani mein ghulne (solubility) mein madad karta hai.",
      "Agar Homogenization zaroorat se zyada ho jaye (Over-homogenization), to fat globules ke 'Clusters' ban jate hain, jisse coffee mein doodh phat sakta hai (feathering).",

      // --- NEW ADDITIONS: CHEESE & FERMENTATION SECRETS (Hinglish) ---
      "Rennet (Chymosin) enzyme specifically Casein micelles ke upar lage 'Kappa-Casein' ke baalon ko kaat deta hai, jisse doodh jam kar curd ban jata hai.",
      "Gouda cheese mein 'Late Blowing' defect Clostridium spores ki wajah se hota hai. Ye spores gas banate hain jisse cheese pakne ke baad andar se phat jati hai.",
      "Processed Cheese banane ke liye natural cheese ko 'Emulsifying Salts' (Citrates/Phosphates) ke saath pighlaya jata hai, taaki wo smooth aur melt hone wala bane.",
      "Yoghurt mein pani chhodna (Syneresis) tab hota hai jab incubation temperature 45°C se zyada ho ya dahi set hone ke baad hila diya gaya ho.",
      "Swiss Cheese mein bade ched (holes/eyes) banane ke liye 'Propionibacterium shermanii' bacteria dala jata hai jo CO2 gas release karta hai.",
      "Italian cheese (jaise Provolone) mein 'Lipase' enzyme jaan-bujh kar dala jata hai taaki fat toot kar ek tej (spicy) flavor de.",
      "Cheddar cheese ka peela/orange rang 'Annatto' (E160b) natural color se aata hai. Ye pH sensitive hota hai aur low pH par pink ho sakta hai.",
      "'Phage-Robust Cultures' wo bacteria strains hote hain jo virus (bacteriophage) se lad sakte hain. Badi factories mein production loss rokne ke liye ye zaroori hain.",
      "Mozzarella ka 'Stretch Test' ye dekhne ke liye hota hai ki casein fibers align hue ya nahi. Agar pH 5.2 se kam hai to cheese toot jayegi, aur 5.7 se zyada hai to rubber jaisi rahegi.",
      "Camembert aur Brie cheese 'Surface Ripened' hoti hain. Inke upar safed mold (Penicillium camemberti) lagaya jata hai jo bahar se andar ki taraf cheese ko soft karta hai.",

      // --- NEW ADDITIONS: QUALITY & ADULTERATION (Hinglish) ---
      "'Alcohol Test' (68-70% ethanol) doodh ki heat stability check karta hai. Agar doodh alcohol ke saath phat jaye, to wo UHT ya boiling ke dauran bhi phat jayega.",
      "Somatic Cell Count (SCC) agar 400,000 se zyada ho to iska matlab hai gaay ko 'Mastitis' (thanela rog) hai. Aise doodh se cheese kam banta hai.",
      "Coliform bacteria 'Hygiene Indicator' hote hain. Pasteurization inhe maar deta hai, to agar packet doodh mein Coliform mile, iska matlab hai packing ke dauran gandagi aayi hai (PPC).",
      "'Resazurin Test' bacteria load check karne ka sabse fast tarika hai. Acha doodh blue rehta hai, kharab doodh jaldi pink ya white ho jata hai.",
      "Agar doodh mein Antibiotics (jaise Penicillin) ke residues hain, to starter culture kaam nahi karega aur dahi ya cheese nahi ban payega.",
      "Melamine ek chemical hai jisme 66% Nitrogen hota hai. Ye protein test (Kjeldahl) ko dhokha dene ke liye milaya jata hai, par ye kidney damage karta hai.",
      "Hydrogen Peroxide ek illegal preservative hai jo bacteria count chupane ke liye use hota hai. Ye doodh ke Vitamin C aur nutrients ko khatam kar deta hai.",
      "Phate hue doodh ko theek karne ke liye 'Neutralizers' (Soda/Caustic) milaye jate hain. Is chori ko pakadne ke liye 'Rosalic Acid Test' kiya jata hai.",
      "Maltodextrin milk powder mein milaya jane wala sasta adulterant hai. Isse pakadne ke liye Iodine test karte hain (ye reddish-brown rang deta hai).",
      "Doodh mein Urea natural hota hai (~20-40 mg), par agar SNF badhane ke liye upar se Urea milaya jaye to 'DMAB Test' se pakda jata hai.",

      // --- NEW ADDITIONS: ICE CREAM & FAT TECHNOLOGY (Hinglish) ---
      "Ice cream mein 'Stabilizers' (Guar Gum/Carrageenan) pani ko baandh kar rakhte hain, taaki storage ke dauran barf ke bade crystals (iciness) na banein.",
      "Ice cream mein 'Emulsifiers' fat globules ko thoda todte hain taaki wo hawa ke bulbulon ke charo taraf chipak sakein, jisse ice cream smooth banti hai.",
      "Ice cream pack karne ke turant baad 'Hardening' (tunnel mein -18°C par jamana) zaroori hai. Agar ye late hua to ice cream ka texture kharab ho jayega.",
      "Iodine Value fat ki hardness batata hai. Bhains ke doodh ka fat Cow milk se hard hota hai, isliye Ghee ke liye acha hai par Table Butter ke liye difficult hai.",
      "Butter mein 'Beta-prime crystals' chahiye hote hain. Agar temperature upar-neeche hua, to ye bade 'Beta crystals' ban jate hain aur makkhan daanedar (grainy) ho jata hai.",
      "'Recrystallization' ice cream ka sabse bada dushman hai. Jab freezer ka gate baar-baar khulta hai, to choti barf pighal kar badi barf ban jati hai (Heat Shock).",
      "Frozen Desserts mein Vegetable Fat use hota hai jiska melting point high hota hai. Agar sahi blend na ho, to ye mooh mein 'waxy' (mom jaisa) feel deta hai.",
      "Condensed milk mein lactose ke bade crystals na bane, isliye 'Seed Lactose' (pise hue lactose powder) ko add kiya jata hai taaki smooth texture rahe.",
      "Buttermilk powder mein 'Phospholipids' bohot hote hain (jo fat membrane se aate hain). Ye bakery products mein egg yolk jaisa kaam karte hain.",

      // --- NEW ADDITIONS: PACKAGING & SHELF LIFE (Hinglish) ---
      "ESL (Extended Shelf Life) milk Pasteurization aur UHT ke beech ki technology hai. Ye 21-45 din tak fridge mein sahi rehta hai.",
      "Milk Powder ke packet ka 'Oxygen Transmission Rate (OTR)' bohot kam hona chahiye. Agar hawa andar gayi, to powder mein se purane tel ki badboo (rancidity) aane lagegi.",
      "Aseptic Packaging (Tetra Pak) 3 layers ka bana hota hai: Paper (shape ke liye), Plastic (seal ke liye), aur Aluminum Foil (light aur oxygen rokne ke liye).",
      "Agar doodh par dhoop ya tube-light padti rahe, to 'Light Oxidation' ho jata hai. Isse doodh mein 'burnt feather' ya 'cabbage' jaisi badboo aati hai.",
      "Milk powder pack karte waqt packet ke andar Oxygen 2% se kam honi chahiye (Headspace Analysis), tabhi wo 1-2 saal tak kharab nahi hoga.",
      "Cheese ke packet mein 'Active Packaging' ka use hota hai, jisme oxygen soakhne wale sachet (scavengers) dale jate hain taaki phaphoondi (mold) na lage.",
      "Doodh ki bottle ke dhakkan par jo seal (band) hoti hai, wo heat tunnel mein shrink ki jati hai. Agar temperature galat hua to bottle ki gardan tedhi ho sakti hai.",
      "Kanch ki bottles (Glass) sabse safe hain par wo light pass karti hain, jisse doodh ka Vitamin B2 (Riboflavin) khatam ho jata hai. Isliye dark glass use karna chahiye.",

      // --- NEW ADDITIONS: WATER & EFFLUENT (Hinglish) ---
      "Dairy ke gande pani (Effluent) mein lactose aur protein hone ki wajah se BOD (Biological Oxygen Demand) bohot high hota hai. Ise bina treat kiye nadi mein nahi fek sakte.",
      "Powder plant mein doodh se jo pani udta hai (Cow Water), use RO se saaf karke wapas plant ki safai ya boiler mein use kiya ja sakta hai.",
      "Pipe saaf karte waqt pehla pani jo doodh ke saath mix hota hai use 'White Water' kehte hain. Ise drain mein fekne ki jagah suaron (pigs) ke khane ya Biogas ke liye use karna chahiye.",
      "Biogas pipes mein aksar 'Struvite' (ek tarah ka pathar) jam jata hai kyunki dairy waste mein Magnesium aur Phosphate bohot zyada hota hai.",
      "Dairy ETP (Treatment Plant) se nikla hua keychad (Sludge) khet ke liye behtareen organic khaad (fertilizer) hai kyunki isme Nitrogen aur Phosphorus bharpoor hota hai."
    ]
  }
};
