export interface DairyCompany {
  id: number;
  name: string;
  category: "cooperative" | "private_dairy" | "ice_cream" | "fmcg_food" | "ingredients" | "global_dairy";
  sector: "Government / Cooperative" | "Private / MNC";
  location: string;
  specialties: string[];
}

export const ALL_350_DAIRY_FOOD_COMPANIES: DairyCompany[] = [
  // 1-24: State Cooperatives & Federations (India)
  { id: 1, name: "Amul / GCMMF", category: "cooperative", sector: "Government / Cooperative", location: "Anand, Gujarat", specialties: ["Liquid Milk", "Butter", "Cheese", "Powder", "Ice Cream"] },
  { id: 2, name: "Kaira District Cooperative Milk Producers' Union", category: "cooperative", sector: "Government / Cooperative", location: "Anand, Gujarat", specialties: ["Raw Milk", "Butter", "Amul Dairy Plant"] },
  { id: 3, name: "Mother Dairy Fruit & Vegetable", category: "cooperative", sector: "Government / Cooperative", location: "Noida, Delhi NCR", specialties: ["Token Milk", "Curd", "Ghee", "Paneer", "Ice Cream"] },
  { id: 4, name: "Karnataka Milk Federation (Nandini)", category: "cooperative", sector: "Government / Cooperative", location: "Bengaluru, Karnataka", specialties: ["Liquid Milk", "GoodLife UHT", "Nandini Sweets", "Ghee"] },
  { id: 5, name: "Tamil Nadu Cooperative Milk Producers' Federation (Aavin)", category: "cooperative", sector: "Government / Cooperative", location: "Chennai, Tamil Nadu", specialties: ["Aavin Milk", "Flavored Milk", "Butter", "Skimmed Milk Powder"] },
  { id: 6, name: "Kerala Co-operative Milk Marketing Federation (Milma)", category: "cooperative", sector: "Government / Cooperative", location: "Thiruvananthapuram, Kerala", specialties: ["Milma Pasteurized Milk", "Sip-Up", "Pedha", "Ghee"] },
  { id: 7, name: "Rajasthan Cooperative Dairy Federation (Saras)", category: "cooperative", sector: "Government / Cooperative", location: "Jaipur, Rajasthan", specialties: ["Saras Milk", "Cow Ghee", "Chach", "Lassi"] },
  { id: 8, name: "Andhra Pradesh Dairy Development Cooperative Federation", category: "cooperative", sector: "Government / Cooperative", location: "Vijayawada, Andhra Pradesh", specialties: ["Vijaya Dairy Milk", "SMP", "Flavored Milk"] },
  { id: 9, name: "Telangana State Dairy Development Cooperative Federation", category: "cooperative", sector: "Government / Cooperative", location: "Hyderabad, Telangana", specialties: ["Vijaya Telangana Milk", "Curd", "Butter Milk"] },
  { id: 10, name: "Odisha State Cooperative Milk Producers' Federation (OMFED)", category: "cooperative", sector: "Government / Cooperative", location: "Bhubaneswar, Odisha", specialties: ["OMFED Toned Milk", "Sweet Curd", "Ghee", "Paneer"] },
  { id: 11, name: "Bihar State Milk Co-operative Federation (COMFED / Sudha)", category: "cooperative", sector: "Government / Cooperative", location: "Patna, Bihar", specialties: ["Sudha Milk", "Sudha Pedha", "Sudha Ice Cream", "Peda"] },
  { id: 12, name: "Punjab State Cooperative Milk Producers' Federation (Verka)", category: "cooperative", sector: "Government / Cooperative", location: "Chandigarh, Punjab", specialties: ["Verka Milk", "Verka Kheer", "Lassi", "Ghee", "SMP"] },
  { id: 13, name: "Haryana Dairy Development Cooperative Federation (Vita)", category: "cooperative", sector: "Government / Cooperative", location: "Panchkula, Haryana", specialties: ["Vita Cow Milk", "Vita Ghee", "Butter", "Curd"] },
  { id: 14, name: "Uttar Pradesh Cooperative Dairy Federation (Parag)", category: "cooperative", sector: "Government / Cooperative", location: "Lucknow, Uttar Pradesh", specialties: ["Parag Gold Milk", "Peda", "Desi Ghee", "Curd"] },
  { id: 15, name: "Madhya Pradesh Cooperative Dairy Federation (Sanchi)", category: "cooperative", sector: "Government / Cooperative", location: "Bhopal, Madhya Pradesh", specialties: ["Sanchi Pasteurized Milk", "Sanchi Shrikhand", "Ghee"] },
  { id: 16, name: "Maharashtra Rajya Sahakari Dudh Mahasangh (Mahanand)", category: "cooperative", sector: "Government / Cooperative", location: "Mumbai, Maharashtra", specialties: ["Mahanand Milk", "Lassi", "Paneer", "Butter"] },
  { id: 17, name: "Gujarat Cooperative Milk Marketing Federation (GCMMF)", category: "cooperative", sector: "Government / Cooperative", location: "Anand, Gujarat", specialties: ["Amul Brand Network", "Export Dairy Operations"] },
  { id: 18, name: "West Assam Milk Producers' Cooperative Union (WAMUL / Purabi)", category: "cooperative", sector: "Government / Cooperative", location: "Guwahati, Assam", specialties: ["Purabi Milk", "Sweet Curd", "Paneer", "Lassi"] },
  { id: 19, name: "West Bengal Cooperative Milk Producers' Federation (Benmilk)", category: "cooperative", sector: "Government / Cooperative", location: "Kolkata, West Bengal", specialties: ["Benmilk Toned Milk", "Ghee", "Milk Peda"] },
  { id: 20, name: "Uttarakhand Cooperative Dairy Federation (Aanchal)", category: "cooperative", sector: "Government / Cooperative", location: "Haldwani, Uttarakhand", specialties: ["Aanchal Milk", "Badam Milk", "Ghee", "Butter"] },
  { id: 21, name: "Himachal Pradesh Milkfed", category: "cooperative", sector: "Government / Cooperative", location: "Shimla, Himachal Pradesh", specialties: ["Milkfed Cow Milk", "Panjiri", "Ghee"] },
  { id: 22, name: "Jammu & Kashmir Milk Producers Cooperative (JKMPCL / Snowcap)", category: "cooperative", sector: "Government / Cooperative", location: "Srinagar & Jammu", specialties: ["Snowcap Pasteurized Milk", "Curd", "Ghee"] },
  { id: 23, name: "Goa Dairy (Goa District Cooperative)", category: "cooperative", sector: "Government / Cooperative", location: "Ponda, Goa", specialties: ["Goa Dairy Milk", "Sterilized Flavored Milk"] },
  { id: 24, name: "Pondicherry Cooperative Milk Producers' Union (PONLAIT)", category: "cooperative", sector: "Government / Cooperative", location: "Puducherry", specialties: ["Ponlait Milk", "Curd", "Ghee", "Ice Cream"] },

  // 25-80: Private & Corporate Dairies (India)
  { id: 25, name: "Dodla Dairy", category: "private_dairy", sector: "Private / MNC", location: "Hyderabad, Telangana", specialties: ["Dodla Milk", "Curd", "Butter", "Ghee", "UHT Milk"] },
  { id: 26, name: "Heritage Foods", category: "private_dairy", sector: "Private / MNC", location: "Hyderabad, Telangana", specialties: ["Heritage Curd", "Flavored Milk", "Paneer", "Milk Powder"] },
  { id: 27, name: "Hatsun Agro Product", category: "private_dairy", sector: "Private / MNC", location: "Chennai, Tamil Nadu", specialties: ["Arokya Milk", "Arun Icecreams", "Oyalo", "HAP Daily"] },
  { id: 28, name: "Parag Milk Foods", category: "private_dairy", sector: "Private / MNC", location: "Manchar, Maharashtra", specialties: ["Gowardhan Ghee", "Go Cheese", "Pride of Cows", "Avvatar Whey"] },
  { id: 29, name: "Milky Mist Dairy Food", category: "private_dairy", sector: "Private / MNC", location: "Erode, Tamil Nadu", specialties: ["Milky Mist Paneer", "Greek Yogurt", "Cheese Slices", "Butter"] },
  { id: 30, name: "Prabhat Dairy", category: "private_dairy", sector: "Private / MNC", location: "Shrirampur, Maharashtra", specialties: ["Prabhat Milk", "Condensed Milk", "Cheese", "Powder"] },
  { id: 31, name: "Creamline Dairy Products (Godrej Jersey)", category: "private_dairy", sector: "Private / MNC", location: "Hyderabad, Telangana", specialties: ["Jersey Milk", "Curd", "Badam Milk", "Ghee"] },
  { id: 32, name: "Tirumala Milk Products (Lactalis India)", category: "private_dairy", sector: "Private / MNC", location: "Chennai, Tamil Nadu", specialties: ["Tirumala Milk", "Curd", "Sweets", "Lactalis Dairy"] },
  { id: 33, name: "Dynamix Dairy Industries (Schreiber Dynamix)", category: "private_dairy", sector: "Private / MNC", location: "Baramati, Maharashtra", specialties: ["UHT Milk", "Cheese", "Infant Formula", "Export Powder"] },
  { id: 34, name: "Kwality Dairy India", category: "private_dairy", sector: "Private / MNC", location: "New Delhi", specialties: ["Kwality Milk", "Ghee", "Skimmed Milk Powder"] },
  { id: 35, name: "Schreiber Dynamix Dairies", category: "private_dairy", sector: "Private / MNC", location: "Baramati, Maharashtra", specialties: ["Contract Dairy Processing", "Aseptic Packaging", "UHT"] },
  { id: 36, name: "Milk Mantra", category: "private_dairy", sector: "Private / MNC", location: "Bhubaneswar, Odisha", specialties: ["Milky Moo", "MooShake", "Curd", "Paneer"] },
  { id: 37, name: "Karnataka Cooperative Milk Federation units", category: "cooperative", sector: "Government / Cooperative", location: "Karnataka District Unions", specialties: ["BAMUL", "KMF Units", "Nandini Processing"] },
  { id: 38, name: "VRS Foods (Paras Dairy)", category: "private_dairy", sector: "Private / MNC", location: "Ghaziabad, UP", specialties: ["Paras Milk", "Desi Ghee", "Paneer", "Curd"] },
  { id: 39, name: "Sterling Agro Industries (Nova Dairy)", category: "private_dairy", sector: "Private / MNC", location: "New Delhi & Malanpur", specialties: ["Nova Ghee", "Nova SMP", "Nova Dairy Whitener"] },
  { id: 40, name: "Nova Dairy", category: "private_dairy", sector: "Private / MNC", location: "UP & MP", specialties: ["Nova Pasteurized Milk", "Butter", "SMP"] },
  { id: 41, name: "Gokul Dairy (Kolhapur Zilla Dudh Sangh)", category: "cooperative", sector: "Government / Cooperative", location: "Kolhapur, Maharashtra", specialties: ["Gokul Buff Milk", "Gokul Cow Milk", "Ghee", "Shrikhand"] },
  { id: 42, name: "Dudhsagar Dairy (Mehsana Union)", category: "cooperative", sector: "Government / Cooperative", location: "Mehsana, Gujarat", specialties: ["Amul Moti", "Amul Gold", "Camel Milk", "SMP Plant"] },
  { id: 43, name: "Panchamrut Dairy (Godhra Union)", category: "cooperative", sector: "Government / Cooperative", location: "Godhra, Gujarat", specialties: ["Liquid Milk", "Ice Cream Plant", "Powder Plant"] },
  { id: 44, name: "AmulFed Dairy (Bhat Mega Dairy)", category: "cooperative", sector: "Government / Cooperative", location: "Gandhinagar, Gujarat", specialties: ["50 Lakh LPH Mega Dairy", "Aseptic UHT", "Spray Drying"] },
  { id: 45, name: "Baroda Dairy (Vadodara Union)", category: "cooperative", sector: "Government / Cooperative", location: "Vadodara, Gujarat", specialties: ["Baroda Milk", "Sugam Sweets", "Chach"] },
  { id: 46, name: "Sumul Dairy (Surat Union)", category: "cooperative", sector: "Government / Cooperative", location: "Surat, Gujarat", specialties: ["Sumul Gold", "Bakery Products", "Ice Cream"] },
  { id: 47, name: "Banas Dairy (Palanpur Union)", category: "cooperative", sector: "Government / Cooperative", location: "Palanpur, Gujarat", specialties: ["Asia's Largest Milk Union", "Banas Honey", "Banas Powder"] },
  { id: 48, name: "Mehsana District Cooperative Milk Producers' Union", category: "cooperative", sector: "Government / Cooperative", location: "Mehsana, Gujarat", specialties: ["Dudhsagar Dairy Network"] },
  { id: 49, name: "Sabarkantha District Cooperative Milk Producers' Union", category: "cooperative", sector: "Government / Cooperative", location: "Himatnagar, Gujarat", specialties: ["Sabar Dairy", "Amul Butter", "Powder Plant"] },
  { id: 50, name: "Dudhdhara Dairy (Bharuch Union)", category: "cooperative", sector: "Government / Cooperative", location: "Bharuch, Gujarat", specialties: ["Dudhdhara Milk", "Ghee", "Buttermilk"] },
  { id: 51, name: "Panchmahal District Cooperative Milk Producers' Union", category: "cooperative", sector: "Government / Cooperative", location: "Godhra, Gujarat", specialties: ["Panchamrut Dairy Network"] },
  { id: 52, name: "Rajkot District Cooperative Milk Producers' Union", category: "cooperative", sector: "Government / Cooperative", location: "Rajkot, Gujarat", specialties: ["Gopal Dairy", "Peda", "Ghee"] },
  { id: 53, name: "Sabar Dairy (Himatnagar)", category: "cooperative", sector: "Government / Cooperative", location: "Himatnagar, Gujarat", specialties: ["Amul Spray", "Liquid Milk Processing"] },
  { id: 54, name: "Mother Dairy Fruit & Vegetable Pvt Ltd", category: "cooperative", sector: "Government / Cooperative", location: "Noida, Delhi NCR", specialties: ["Safal", "Dhara Oils", "Mother Dairy Milk"] },
  { id: 55, name: "Goa State Cooperative Milk Producers' Union", category: "cooperative", sector: "Government / Cooperative", location: "Curti, Ponda, Goa", specialties: ["Goa Dairy Pasteurized Milk"] },
  { id: 56, name: "Milky Mist", category: "private_dairy", sector: "Private / MNC", location: "Perundurai, Tamil Nadu", specialties: ["Mega Automation Dairy", "Mozzarella", "Yogurt"] },
  { id: 57, name: "Ananda Dairy", category: "private_dairy", sector: "Private / MNC", location: "Bulandshahr, UP", specialties: ["Ananda Milk", "Ananda Ghee", "Paneer", "Rabri"] },
  { id: 58, name: "Gyan Dairy (CP Milk & Food Products)", category: "private_dairy", sector: "Private / MNC", location: "Lucknow, UP", specialties: ["Gyan Fresh Milk", "Gyan Lassi", "Khoya", "Butter"] },
  { id: 59, name: "Paras Dairy (VRS Foods)", category: "private_dairy", sector: "Private / MNC", location: "Noida, UP", specialties: ["Paras Fresh Milk", "Chach", "Paneer"] },
  { id: 60, name: "Anik Industries", category: "private_dairy", sector: "Private / MNC", location: "Indore, MP", specialties: ["Anik Spray", "Anik Ghee", "Dairy Whitener"] },
  { id: 61, name: "Dairy Classic Ice Creams (Dairy Day)", category: "ice_cream", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Dairy Day Ice Cream", "Frozen Desserts"] },
  { id: 62, name: "A-One Dairy", category: "private_dairy", sector: "Private / MNC", location: "Gujarat & UP", specialties: ["Fresh Milk", "Ghee Processing"] },
  { id: 63, name: "Country Delight", category: "private_dairy", sector: "Private / MNC", location: "Gurugram, Delhi NCR", specialties: ["Direct Farm-to-Home Milk", "A2 Cow Milk", "Desi Danedar Ghee"] },
  { id: 64, name: "Ananda Milk Union", category: "private_dairy", sector: "Private / MNC", location: "UP & Delhi NCR", specialties: ["Ananda Dairy Network"] },
  { id: 65, name: "Gopaljee Dairy Foods", category: "private_dairy", sector: "Private / MNC", location: "Faridabad, Haryana", specialties: ["Ananda Gopaljee Milk", "Curd", "SMP"] },
  { id: 66, name: "Madhusudan Dairy (SMV Dairies)", category: "private_dairy", sector: "Private / MNC", location: "Bulandshahr, UP", specialties: ["Madhusudan Ghee", "Milk Powder"] },
  { id: 67, name: "Nova Milk (Sterling Agro)", category: "private_dairy", sector: "Private / MNC", location: "New Delhi", specialties: ["Nova Pure Cow Milk", "Desi Ghee"] },
  { id: 68, name: "Namaste India Foods (RSPL Group)", category: "private_dairy", sector: "Private / MNC", location: "Kanpur, UP", specialties: ["Namaste India Milk", "Ghee", "Paneer", "Dahi"] },
  { id: 69, name: "Dynamic Dairy", category: "private_dairy", sector: "Private / MNC", location: "Baramati, Maharashtra", specialties: ["Processed Cheese", "Casein"] },
  { id: 70, name: "Milkfood Ltd", category: "private_dairy", sector: "Private / MNC", location: "Patiala, Punjab", specialties: ["Milkfood Ghee", "Full Cream Powder", "Infant Food"] },
  { id: 71, name: "Modern Dairies", category: "private_dairy", sector: "Private / MNC", location: "Karnal, Haryana", specialties: ["Liquid Milk", "Casein", "Lactose", "Export SMP"] },
  { id: 72, name: "Schreiber India", category: "private_dairy", sector: "Private / MNC", location: "Baramati, Maharashtra", specialties: ["Schreiber Dynamix Aseptic Packaging"] },
  { id: 73, name: "Royal Dairy Products", category: "private_dairy", sector: "Private / MNC", location: "Gujarat", specialties: ["Processing & Sweets"] },
  { id: 74, name: "Sterling Agro", category: "private_dairy", sector: "Private / MNC", location: "Delhi NCR", specialties: ["Nova Brand Dairy Products"] },
  { id: 75, name: "Anmol Dairy", category: "private_dairy", sector: "Private / MNC", location: "UP & MP", specialties: ["Anmol Ghee", "Fresh Milk"] },
  { id: 76, name: "Vimal Dairy", category: "private_dairy", sector: "Private / MNC", location: "Mehsana, Gujarat", specialties: ["Vimal Milk", "Ice Cream", "UHT Milk"] },
  { id: 77, name: "Keventer Agro", category: "private_dairy", sector: "Private / MNC", location: "Kolkata, West Bengal", specialties: ["Metro Dairy", "Keventer Banana", "Frooti Franchise"] },
  { id: 78, name: "Bengal Nestor's Industries", category: "private_dairy", sector: "Private / MNC", location: "Kolkata, West Bengal", specialties: ["Dairy Whitener", "Condensed Milk"] },
  { id: 79, name: "Metro Dairy (Keventer)", category: "private_dairy", sector: "Private / MNC", location: "Barasat, West Bengal", specialties: ["Metro Pasteurized Milk", "Ice Cream"] },
  { id: 80, name: "Haringhata Farm (WB Livestock Dev Corp)", category: "cooperative", sector: "Government / Cooperative", location: "Haringhata, West Bengal", specialties: ["Haringhata Milk", "Meat & Dairy Processing"] },

  // 81-110: Ice Cream & Frozen Dessert Leaders
  { id: 81, name: "Hindustan Unilever (HUL)", category: "ice_cream", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Kwality Wall's", "Cornetto", "Feast", "Magnum"] },
  { id: 82, name: "Kwality Wall's", category: "ice_cream", sector: "Private / MNC", location: "All India Network", specialties: ["Frozen Desserts", "Cornetto", "Cassatta"] },
  { id: 83, name: "Arun Icecreams (Hatsun Agro)", category: "ice_cream", sector: "Private / MNC", location: "Chennai, Tamil Nadu", specialties: ["Arun Ice Cream Parlors", "Ibar", "Cassatta"] },
  { id: 84, name: "Havmor Ice Cream (Lotte Wellfood)", category: "ice_cream", sector: "Private / MNC", location: "Ahmedabad, Gujarat", specialties: ["Havmor Kulfi", "Ice Cream Cakes", "Lotte Havmor"] },
  { id: 85, name: "Hocco Ice Cream", category: "ice_cream", sector: "Private / MNC", location: "Ahmedabad, Gujarat", specialties: ["Hocco Ice Cream", "Choco Bar", "Cone"] },
  { id: 86, name: "Vadilal Industries", category: "ice_cream", sector: "Private / MNC", location: "Ahmedabad, Gujarat", specialties: ["Vadilal Ice Cream", "Gourmet Tubs", "Quick Treat"] },
  { id: 87, name: "Vadilal Enterprises", category: "ice_cream", sector: "Private / MNC", location: "Ahmedabad, Gujarat", specialties: ["Vadilal Distribution & Cold Chain"] },
  { id: 88, name: "Creambell (Devyani Food Industries)", category: "ice_cream", sector: "Private / MNC", location: "New Delhi", specialties: ["Creambell Cones", "Choco Fudge", "Ice Cream Tubs"] },
  { id: 89, name: "Dinshaw's Dairy Foods", category: "ice_cream", sector: "Private / MNC", location: "Nagpur, Maharashtra", specialties: ["Dinshaw's Premium Ice Cream", "Milk Products"] },
  { id: 90, name: "Dairy Day (Dairy Classic Ice Creams)", category: "ice_cream", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Dairy Day Cones", "Kulfi", "Family Packs"] },
  { id: 91, name: "Naturals Ice Cream (Kamaths Our Times)", category: "ice_cream", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Tender Coconut Ice Cream", "Sitaphal", "Mango Naturals"] },
  { id: 92, name: "NIC Ice Creams (Walko Food Company)", category: "ice_cream", sector: "Private / MNC", location: "Pune, Maharashtra", specialties: ["NIC Honestly Natural Ice Creams", "Choco Chips"] },
  { id: 93, name: "Go Zero (Zero Sugar Ice Creams)", category: "ice_cream", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Keto Ice Cream", "Zero Sugar Desserts"] },
  { id: 94, name: "Hangyo Ice Creams", category: "ice_cream", sector: "Private / MNC", location: "Mangaluru, Karnataka", specialties: ["Hangyo Gourmet Ice Creams", "Kulfi"] },
  { id: 95, name: "Cream Stone", category: "ice_cream", sector: "Private / MNC", location: "Hyderabad, Telangana", specialties: ["Handcrafted Stone Concepts", "Waffle Cones"] },
  { id: 96, name: "Top 'N Town", category: "ice_cream", sector: "Private / MNC", location: "Bhopal, MP", specialties: ["Top 'N Town Ice Cream Parlors"] },
  { id: 97, name: "Scoops Ice Cream", category: "ice_cream", sector: "Private / MNC", location: "Hyderabad, Telangana", specialties: ["Scoops Dairy Ice Cream"] },
  { id: 98, name: "Ideal Ice Cream", category: "ice_cream", sector: "Private / MNC", location: "Mangaluru, Karnataka", specialties: ["Ideal Gadbad", "Tiramisu Ice Cream"] },
  { id: 99, name: "Sudha Ice Cream (COMFED)", category: "cooperative", sector: "Government / Cooperative", location: "Patna, Bihar", specialties: ["Sudha Vanilla", "Butterscotch Cones"] },
  { id: 100, name: "Mother Dairy Ice Cream", category: "cooperative", sector: "Government / Cooperative", location: "Noida, UP", specialties: ["Chillz Cones", "Cassatta", "Kulfi"] },
  { id: 101, name: "Amul Ice Cream (GCMMF)", category: "cooperative", sector: "Government / Cooperative", location: "Anand, Gujarat", specialties: ["Amul Real Milk Ice Cream", "Epic Ice Cream"] },
  { id: 102, name: "Giani's", category: "ice_cream", sector: "Private / MNC", location: "Delhi NCR", specialties: ["Giani Rabri Faluda", "Ice Cream Parlors"] },
  { id: 103, name: "Cocoberry", category: "ice_cream", sector: "Private / MNC", location: "New Delhi", specialties: ["Frozen Yogurt", "Smoothies"] },
  { id: 104, name: "Polar Bear", category: "ice_cream", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Polar Bear Sundaes", "Ice Cream Zone"] },
  { id: 105, name: "Milano Ice Cream", category: "ice_cream", sector: "Private / MNC", location: "Kochi, Kerala", specialties: ["Italian Gelato", "Sorbets"] },
  { id: 106, name: "London Dairy India (IFFCO)", category: "ice_cream", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["London Dairy Premium Tub", "Double Chocolate"] },
  { id: 107, name: "Baskin-Robbins India (Graviss Foods)", category: "ice_cream", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["31 Flavors", "Mississippi Mud", "Baskin Cones"] },
  { id: 108, name: "Magnum India (HUL)", category: "ice_cream", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Magnum Almond", "Belgian Chocolate"] },
  { id: 109, name: "Cornetto India (HUL)", category: "ice_cream", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Cornetto Disc", "Chocolate Tip"] },
  { id: 110, name: "Creamy Inn", category: "ice_cream", sector: "Private / MNC", location: "South India", specialties: ["Soft Serve", "Ice Cream"] },

  // 111-170: FMCG, Food & Bakery Giants (India)
  { id: 111, name: "Nestlé India", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Everyday Dairy Whitener", "Nescafé", "Maggi", "Cerelac", "KitKat"] },
  { id: 112, name: "Britannia Industries", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Britannia Cheese", "Winkies", "Good Day", "Bourbon", "NutriChoice"] },
  { id: 113, name: "ITC Limited (ITC Food Division)", category: "fmcg_food", sector: "Private / MNC", location: "Kolkata, West Bengal", specialties: ["Aashirvaad Svasti Milk", "Sunfeast", "B Natural", "Bingo"] },
  { id: 114, name: "Tata Consumer Products", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Tata Salt", "Tata Tea", "Tata Sampann", "Himalayan Water"] },
  { id: 115, name: "PepsiCo India", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Lay's", "Kurkure", "Quaker Oats", "Tropicana", "Pepsi"] },
  { id: 116, name: "Coca-Cola India", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Vio Dairy Drink", "Minute Maid", "Maaza", "Coke"] },
  { id: 117, name: "Mondelez India (Cadbury)", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Cadbury Dairy Milk", "Bournvita", "Oreo", "5 Star"] },
  { id: 118, name: "Dabur India", category: "fmcg_food", sector: "Private / MNC", location: "Ghaziabad, UP", specialties: ["Real Fruit Juice", "Dabur Honey", "Chyawanprash"] },
  { id: 119, name: "Marico", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Saffola Oats", "Saffola Cooking Oil", "Coco Soul"] },
  { id: 120, name: "Emami Agrotech", category: "fmcg_food", sector: "Private / MNC", location: "Kolkata, West Bengal", specialties: ["Healthy & Tasty Oil", "Mantra Spices"] },
  { id: 121, name: "Patanjali Foods (Ruchi Soya)", category: "fmcg_food", sector: "Private / MNC", location: "Haridwar, Uttarakhand", specialties: ["Patanjali Cow Ghee", "Patanjali Milk", "Nutrela", "Honey"] },
  { id: 122, name: "Adani Wilmar (Fortune)", category: "fmcg_food", sector: "Private / MNC", location: "Ahmedabad, Gujarat", specialties: ["Fortune Oil", "Fortune Besan", "Rice", "Sugar"] },
  { id: 123, name: "AWL Agri Business", category: "fmcg_food", sector: "Private / MNC", location: "Ahmedabad, Gujarat", specialties: ["Agri Trading", "Edible Oils"] },
  { id: 124, name: "MTR Foods (Orkla)", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Ready-to-Eat", "Gulab Jamun Mix", "Spices"] },
  { id: 125, name: "LT Foods (Daawat Basmati)", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Daawat Basmati Rice", "Devaya", "Kari Kari"] },
  { id: 126, name: "Bikaji Foods International", category: "fmcg_food", sector: "Private / MNC", location: "Bikaner, Rajasthan", specialties: ["Bikaji Bhujia", "Sweets", "Namkeen", "Papad"] },
  { id: 127, name: "Haldiram's (Nagpur & Delhi)", category: "fmcg_food", sector: "Private / MNC", location: "Nagpur & Noida", specialties: ["Haldiram Sweets", "Soan Papdi", "Rasgulla", "Frozen Meals"] },
  { id: 128, name: "Balaji Wafers", category: "fmcg_food", sector: "Private / MNC", location: "Rajkot, Gujarat", specialties: ["Potato Chips", "Wafers", "Namkeen"] },
  { id: 129, name: "Balaji Foods", category: "fmcg_food", sector: "Private / MNC", location: "Gujarat", specialties: ["Snack Processing"] },
  { id: 130, name: "Parle Products", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Parle-G", "Hide & Seek", "Monaco", "Krackjack"] },
  { id: 131, name: "Priya Gold (Surya Food & Agro)", category: "fmcg_food", sector: "Private / MNC", location: "Noida, UP", specialties: ["Priya Gold Biscuits", "CNC", "Snakker"] },
  { id: 132, name: "Cremica Food Industries", category: "fmcg_food", sector: "Private / MNC", location: "Ludhiyana, Punjab", specialties: ["Cremica Sauces", "Mayonnaise", "Biscuits", "Syrups"] },
  { id: 133, name: "Mrs. Bector's Food Specialities (Cremica / English Oven)", category: "fmcg_food", sector: "Private / MNC", location: "Ludhiana, Punjab", specialties: ["English Oven Bread", "Cremica Biscuits"] },
  { id: 134, name: "Dukes / Ravi Foods", category: "fmcg_food", sector: "Private / MNC", location: "Hyderabad, Telangana", specialties: ["Dukes Wafers", "Biscuits", "Confectionery"] },
  { id: 135, name: "Bonn Group of Industries", category: "fmcg_food", sector: "Private / MNC", location: "Ludhiana, Punjab", specialties: ["Bonn Bread", "Cookies", "Bonn Cream Biscuits"] },
  { id: 136, name: "Harvest Gold (Grupo Bimbo)", category: "fmcg_food", sector: "Private / MNC", location: "Noida, UP", specialties: ["Harvest Gold Brown Bread", "Garlic Bread", "Buns"] },
  { id: 137, name: "Modern Foods (Biocon / Grupo Bimbo)", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Modern Bread", "Milk Bread", "Cakes"] },
  { id: 138, name: "Veeba Foods (VRB Consumer Products)", category: "fmcg_food", sector: "Private / MNC", location: "Neemrana, Rajasthan", specialties: ["Veeba Salad Dressings", "Chef's Special Ketchup", "Mayonnaise"] },
  { id: 139, name: "Wingreens Farms", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Dips", "Hummus", "Pasta Sauces", "Monsoon Harvest"] },
  { id: 140, name: "iD Fresh Food", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Idly-Dosa Batter", "Malabar Parota", "Paneer", "Filter Coffee"] },
  { id: 141, name: "Epigamia (Drums Food International)", category: "private_dairy", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Epigamia Greek Yogurt", "Smoothies", "Ghee Spread", "Milkshakes"] },
  { id: 142, name: "Country Delight Foods", category: "private_dairy", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["A2 Cow Milk", "Buffalo Milk", "Paneer", "Taaza Dahi"] },
  { id: 143, name: "Yogabar (Sproutlife / ITC)", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Protein Bars", "Muesli", "Peanut Butter"] },
  { id: 144, name: "Paper Boat (Hector Beverages)", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Aamras", "Anardana", "Chhoti Anardana", "Coconut Water"] },
  { id: 145, name: "Raw Pressery (Dharmapal Satyapal)", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Cold-Pressed Juices", "Almond Milk", "Protein Shakes"] },
  { id: 146, name: "Hector Beverages", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Paper Boat Juices & Traditional Drinks"] },
  { id: 147, name: "Amul Foods Division", category: "cooperative", sector: "Government / Cooperative", location: "Anand, Gujarat", specialties: ["Amul Chocolates", "Amul Bakery", "Amul Mithai Mate"] },
  { id: 148, name: "Cremica Agro", category: "fmcg_food", sector: "Private / MNC", location: "Punjab", specialties: ["Condiments & Food Processing"] },
  { id: 149, name: "Veeba Consumer", category: "fmcg_food", sector: "Private / MNC", location: "Rajasthan", specialties: ["Sauces & Dips"] },
  { id: 150, name: "Wingreens World", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram", specialties: ["Snacks & Dips"] },
  { id: 151, name: "Parle Products Pvt Ltd", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai", specialties: ["Parle G", "Fab", "Platina"] },
  { id: 152, name: "Britannia Foods", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru", specialties: ["Croissants", "Dairy Cheese", "Little Hearts"] },
  { id: 153, name: "ITC Sunfeast", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru", specialties: ["Dark Fantasy", "Mom's Magic", "Sunfeast Bounce"] },
  { id: 154, name: "Priya Gold Biscuits", category: "fmcg_food", sector: "Private / MNC", location: "Noida", specialties: ["Biscuits & Confectionery"] },
  { id: 155, name: "Anmol Industries", category: "fmcg_food", sector: "Private / MNC", location: "Kolkata, WB", specialties: ["Anmol Biscuits", "Dream Lite", "Twinz"] },
  { id: 156, name: "Bonn Nutritious", category: "fmcg_food", sector: "Private / MNC", location: "Ludhiana", specialties: ["Americana Biscuits", "Brown Bread"] },
  { id: 157, name: "Harvest Gold Bakery", category: "fmcg_food", sector: "Private / MNC", location: "Noida", specialties: ["White & Wheat Breads"] },
  { id: 158, name: "Modern Food Enterprises", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram", specialties: ["Modern Bakery & Breads"] },
  { id: 159, name: "Mrs. Bector's Specialities", category: "fmcg_food", sector: "Private / MNC", location: "Ludhiana", specialties: ["Cremica Cookies", "Buns"] },
  { id: 160, name: "Monginis Foods", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Monginis Cakes", "Pastries", "Savories"] },
  { id: 161, name: "Mio Amore (Green Dot Bakeries)", category: "fmcg_food", sector: "Private / MNC", location: "Kolkata, West Bengal", specialties: ["Mio Amore Cakes", "Patties", "Rolls"] },
  { id: 162, name: "Karachi Bakery", category: "fmcg_food", sector: "Private / MNC", location: "Hyderabad, Telangana", specialties: ["Fruit Biscuits", "Dilkush", "Plum Cakes"] },
  { id: 163, name: "Theobroma Foods", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Brownies", "Artisanal Breads", "Macarons"] },
  { id: 164, name: "Spencers Bakery", category: "fmcg_food", sector: "Private / MNC", location: "Kolkata, WB", specialties: ["Fresh Bakery Items"] },
  { id: 165, name: "Winkies (Switz Foods)", category: "fmcg_food", sector: "Private / MNC", location: "Kolkata, WB", specialties: ["Winkies Swiss Rolls", "Cupcakes", "Slice Cakes"] },
  { id: 166, name: "Dukes Wafers", category: "fmcg_food", sector: "Private / MNC", location: "Hyderabad", specialties: ["Wafers & Biscuits"] },
  { id: 167, name: "Unibic India", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru, Karnataka", specialties: ["Unibic Cookie Magic", "Choco Chip", "Oatmeal Cookies"] },
  { id: 168, name: "Cremica Biscuit Division", category: "fmcg_food", sector: "Private / MNC", location: "Punjab", specialties: ["Glucose & Cream Biscuits"] },
  { id: 169, name: "BakeMate (Ravi Foods)", category: "fmcg_food", sector: "Private / MNC", location: "Hyderabad", specialties: ["BakeMate Biscuits & Chocolates"] },
  { id: 170, name: "Monginis India", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai", specialties: ["Bakery Chain & Franchises"] },

  // 171-195: Beverage & Juice Processing Giants
  { id: 171, name: "Dabur Foods (Real)", category: "fmcg_food", sector: "Private / MNC", location: "Ghaziabad, UP", specialties: ["Real Fruit Power", "Real Activ", "Real Aloe Vera"] },
  { id: 172, name: "PepsiCo India Beverage Division", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram", specialties: ["Tropicana 100%", "Gatorade", "Aquafina"] },
  { id: 173, name: "Coca-Cola India Beverage", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram", specialties: ["Maaza Mango Juice", "Minute Maid Pulpy Orange", "Kinley"] },
  { id: 174, name: "Parle Agro", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Frooti Mango Juice", "Appy Fizz", "B-Fizz", "Bailley Water"] },
  { id: 175, name: "Paper Boat (Hector)", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru", specialties: ["Traditional Indian Juices", "Paper Boat Coconut"] },
  { id: 176, name: "Real / Dabur India", category: "fmcg_food", sector: "Private / MNC", location: "UP", specialties: ["Aseptic PET & Tetra Pak Juices"] },
  { id: 177, name: "Tropicana India (PepsiCo)", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram", specialties: ["Tropicana Juices & Nectars"] },
  { id: 178, name: "Minute Maid India (Coca-Cola)", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram", specialties: ["Minute Maid Pulpy", "Guava Juice"] },
  { id: 179, name: "Maaza (Coca-Cola)", category: "fmcg_food", sector: "Private / MNC", location: "All India Bottling Units", specialties: ["Maaza Mango Drink"] },
  { id: 180, name: "Slice (PepsiCo)", category: "fmcg_food", sector: "Private / MNC", location: "All India Units", specialties: ["Slice Mango Drink"] },
  { id: 181, name: "Frooti (Parle Agro)", category: "fmcg_food", sector: "Private / MNC", location: "All India Units", specialties: ["Frooti Mango Drink in Tetra Pak"] },
  { id: 182, name: "Appy Fizz (Parle Agro)", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai", specialties: ["Sparkling Apple Juice Drink"] },
  { id: 183, name: "Lahori Zeera (Lahori Drinks)", category: "fmcg_food", sector: "Private / MNC", location: "Rupnagar, Punjab", specialties: ["Lahori Zeera", "Desi Carbonated Drinks"] },
  { id: 184, name: "Hector Beverages (Paper Boat)", category: "fmcg_food", sector: "Private / MNC", location: "Mysuru & Gurugram", specialties: ["Traditional Beverage Plants"] },
  { id: 185, name: "Raw Pressery Cold-Pressed", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai", specialties: ["Cold Pressed HPP Technology Juices"] },
  { id: 186, name: "Paper Boat Drinks", category: "fmcg_food", sector: "Private / MNC", location: "Bengaluru", specialties: ["Aseptic Pouch Filling"] },
  { id: 187, name: "Bisleri International", category: "fmcg_food", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Bisleri Packaged Water", "Vedica", "Limonata", "Fonzo"] },
  { id: 188, name: "Manpasand Beverages", category: "fmcg_food", sector: "Private / MNC", location: "Vadodara, Gujarat", specialties: ["Mango Sip", "Fruits Up"] },
  { id: 189, name: "Varun Beverages (RJ Corp)", category: "fmcg_food", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["PepsiCo Franchised Bottling", "Sting Energy", "Slice"] },
  { id: 190, name: "Hector Beverages Plant", category: "fmcg_food", sector: "Private / MNC", location: "Karnataka", specialties: ["Beverage Bottling"] },
  { id: 191, name: "Coca-Cola Bottling India", category: "fmcg_food", sector: "Private / MNC", location: "Pan-India Plants", specialties: ["Hindustan Coca-Cola Beverages (HCCB)"] },
  { id: 192, name: "PepsiCo India Plants", category: "fmcg_food", sector: "Private / MNC", location: "Pan-India Plants", specialties: ["Varun Beverages & PepsiCo Manufacturing"] },
  { id: 193, name: "Bisleri Packaged Water", category: "fmcg_food", sector: "Private / MNC", location: "Pan-India Plants", specialties: ["Ozonated Mineral Water Processing"] },
  { id: 194, name: "Parle Agro Plants", category: "fmcg_food", sector: "Private / MNC", location: "Pan-India Plants", specialties: ["Aseptic Filling Lines"] },
  { id: 195, name: "Manpasand Juice Lines", category: "fmcg_food", sector: "Private / MNC", location: "Gujarat", specialties: ["Juice & Nectar Lines"] },

  // 196-210: Agri-Business & Food Ingredients Leaders (India)
  { id: 196, name: "Olam Agri India", category: "ingredients", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Cocoa", "Coffee", "Dairy Ingredients", "Edible Oils"] },
  { id: 197, name: "Cargill India", category: "ingredients", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Cargill Starches", "PuraVita", "NatureFresh Oil", "Texturizers"] },
  { id: 198, name: "ADM India (Archer Daniels Midland)", category: "ingredients", sector: "Private / MNC", location: "Gurugram, Haryana", specialties: ["Soy Protein", "Flavor Systems", "Emulsifiers"] },
  { id: 199, name: "Ingredion India", category: "ingredients", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Modified Starches", "Hydrocolloids", "Sweeteners"] },
  { id: 200, name: "Kerry India (Kerry Group)", category: "ingredients", sector: "Private / MNC", location: "Gurugram & Bengaluru", specialties: ["Taste & Nutrition", "Dairy Flavors", "Savory Systems"] },
  { id: 201, name: "DSM-Firmenich India", category: "ingredients", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Dairy Enzymes (Lactase)", "Vitamins", "Culture Systems"] },
  { id: 202, name: "Tate & Lyle India", category: "ingredients", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["SPLENDA Sucralose", "Fiber", "Stabilizers for Dairy"] },
  { id: 203, name: "IFF India (International Flavors & Fragrances)", category: "ingredients", sector: "Private / MNC", location: "Chennai & Mumbai", specialties: ["DANISCO Cultures & Enzymes", "Pectin", "Flavors"] },
  { id: 204, name: "Givaudan India", category: "ingredients", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Flavors for Dairy", "Beverage Flavors", "Vanilla"] },
  { id: 205, name: "Symrise India", category: "ingredients", sector: "Private / MNC", location: "Chennai, Tamil Nadu", specialties: ["Fruit Preparations", "Beverage & Ice Cream Flavors"] },
  { id: 206, name: "AAK India (AarhusKarlshamn)", category: "ingredients", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Specialty Fats for Ice Cream & Chocolate"] },
  { id: 207, name: "Corbion India", category: "ingredients", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Lactic Acid", "Preservatives", "Emulsifiers"] },
  { id: 208, name: "Roquette India", category: "ingredients", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Pea Protein", "Polyols (Maltitol)", "Wheat Starch"] },
  { id: 209, name: "Puratos India", category: "ingredients", sector: "Private / MNC", location: "Mumbai, Maharashtra", specialties: ["Bakery Ingredients", "Chocolate", "Fruit Fillings"] },
  { id: 210, name: "Barry Callebaut India", category: "ingredients", sector: "Private / MNC", location: "Pune, Maharashtra", specialties: ["Industrial Chocolate", "Cocoa Powder", "Compound Chocolate"] },

  // 211-250: Global International Dairy & Food Titans (Global)
  { id: 211, name: "Lactalis Group — France", category: "global_dairy", sector: "Private / MNC", location: "Laval, France", specialties: ["World's Largest Dairy Company", "President Cheese", "Parmalat"] },
  { id: 212, name: "Nestlé — Switzerland", category: "global_dairy", sector: "Private / MNC", location: "Vevey, Switzerland", specialties: ["Global Food & Dairy Giant", "Nido", "Carnation", "Gerber"] },
  { id: 213, name: "Dairy Farmers of America — USA", category: "global_dairy", sector: "Government / Cooperative", location: "Kansas City, USA", specialties: ["Largest US Dairy Cooperative", "Borden Milk", "Hotel Bar Butter"] },
  { id: 214, name: "Danone — France", category: "global_dairy", sector: "Private / MNC", location: "Paris, France", specialties: ["Activia Yogurt", "Danette", "Aptamil", "Silk Plant Milk"] },
  { id: 215, name: "Yili Group — China", category: "global_dairy", sector: "Private / MNC", location: "Hohhot, China", specialties: ["Asia's Top Dairy", "AMPOMULTA UHT", "Yili Organic Milk"] },
  { id: 216, name: "Fonterra — New Zealand", category: "global_dairy", sector: "Government / Cooperative", location: "Auckland, New Zealand", specialties: ["World's Largest Dairy Exporter", "Anchor", "NZMP Ingredients"] },
  { id: 217, name: "Arla Foods — Denmark", category: "global_dairy", sector: "Government / Cooperative", location: "Viby, Denmark", specialties: ["Lurpak Butter", "Castello Cheese", "Arla Organic"] },
  { id: 218, name: "FrieslandCampina — Netherlands", category: "global_dairy", sector: "Government / Cooperative", location: "Amersfoort, Netherlands", specialties: ["Peak Milk", "Dutch Lady", "Friso Infant Nutrition"] },
  { id: 219, name: "China Mengniu Dairy — China", category: "global_dairy", sector: "Private / MNC", location: "Hong Kong & China", specialties: ["Mengniu Milk", "Telunsu UHT", "Yoyi C Yogurt"] },
  { id: 220, name: "Saputo — Canada", category: "global_dairy", sector: "Private / MNC", location: "Montreal, Canada", specialties: ["Saputo Cheese", "Dairyland", "Armstrong", "Cathedral City"] },
  { id: 221, name: "Unilever — UK / Netherlands", category: "global_dairy", sector: "Private / MNC", location: "London & Rotterdam", specialties: ["Ben & Jerry's", "Breyers", "Magnum", "Walls"] },
  { id: 222, name: "Schreiber Foods — USA", category: "global_dairy", sector: "Private / MNC", location: "Green Bay, Wisconsin", specialties: ["Global Private Label Cheese & Yogurt"] },
  { id: 223, name: "Savencia Fromage & Dairy — France", category: "global_dairy", sector: "Private / MNC", location: "Viroflay, France", specialties: ["Specialty Cheese", "Elle & Vire", "Caprice des Dieux"] },
  { id: 224, name: "Müller — Germany / UK", category: "global_dairy", sector: "Private / MNC", location: "Fischach, Germany", specialties: ["Müller Corner Yogurt", "Müller Rice", "Milk Drinks"] },
  { id: 225, name: "Sodiaal — France", category: "global_dairy", sector: "Government / Cooperative", location: "Paris, France", specialties: ["Candia Milk", "Yoplait France", "Entremont Cheese"] },
  { id: 226, name: "Agropur — Canada", category: "global_dairy", sector: "Government / Cooperative", location: "Longueuil, Canada", specialties: ["Natrel Milk", "iGO Yogurt", "Agropur Cheese"] },
  { id: 227, name: "DMK Deutsches Milchkontor — Germany", category: "global_dairy", sector: "Government / Cooperative", location: "Bremen, Germany", specialties: ["Milram Cheese", "Humana Baby Food", "Oldenburger"] },
  { id: 228, name: "Froneri — UK / Switzerland", category: "global_dairy", sector: "Private / MNC", location: "Leeming Bar, UK", specialties: ["Nestlé Ice Cream JV", "Mövenpick", "Cadbury Ice Cream"] },
  { id: 229, name: "Grupo Lala — Mexico", category: "global_dairy", sector: "Private / MNC", location: "Mexico City", specialties: ["Lala Fresh Milk", "Nutri Leche", "Yogurt Drinks"] },
  { id: 230, name: "Glanbia — Ireland", category: "global_dairy", sector: "Private / MNC", location: "Kilkenny, Ireland", specialties: ["Optimum Nutrition Whey", "Glanbia Ingredients Ireland"] },
  { id: 231, name: "Ornua — Ireland", category: "global_dairy", sector: "Government / Cooperative", location: "Dublin, Ireland", specialties: ["Kerrygold Irish Butter", "Kerrygold Cheese"] },
  { id: 232, name: "Emmi Group — Switzerland", category: "global_dairy", sector: "Private / MNC", location: "Lucerne, Switzerland", specialties: ["Emmi Caffè Latte", "Swiss Fondue", "Kaltbach Cheese"] },
  { id: 233, name: "Hochland — Germany", category: "global_dairy", sector: "Private / MNC", location: "Heimenkirch, Germany", specialties: ["Hochland Cheese Slices", "Almette Cream Cheese"] },
  { id: 234, name: "Megmilk Snow Brand — Japan", category: "global_dairy", sector: "Private / MNC", location: "Tokyo, Japan", specialties: ["Snow Brand Milk", "Neosoft Butter", "Japanese Cheese"] },
  { id: 235, name: "Morinaga Milk Industry — Japan", category: "global_dairy", sector: "Private / MNC", location: "Tokyo, Japan", specialties: ["Bifidus Yogurt", "Morinaga Tofu", "Infant Formula"] },
  { id: 236, name: "Meiji Holdings — Japan", category: "global_dairy", sector: "Private / MNC", location: "Tokyo, Japan", specialties: ["Meiji Bulgaria Yogurt", "Meiji Milk", "Meiji Chocolate"] },
  { id: 237, name: "Megmilk Snow Brand Co", category: "global_dairy", sector: "Private / MNC", location: "Sapporo, Japan", specialties: ["Hokkaido Milk & Butter"] },
  { id: 238, name: "Bongrain / Savencia", category: "global_dairy", sector: "Private / MNC", location: "France", specialties: ["Tartare", "St Moret Cheese"] },
  { id: 239, name: "Lactalis American Group", category: "global_dairy", sector: "Private / MNC", location: "Buffalo, NY, USA", specialties: ["Galbani Mozzarella", "Sorrento Cheese"] },
  { id: 240, name: "Bel Group — France", category: "global_dairy", sector: "Private / MNC", location: "Paris, France", specialties: ["The Laughing Cow (La Vache qui rit)", "Babybel", "Kiri"] },
  { id: 241, name: "Valio — Finland", category: "global_dairy", sector: "Government / Cooperative", location: "Helsinki, Finland", specialties: ["Lactose-Free Milk (EILA)", "Valio Butter", "Oddlygood"] },
  { id: 242, name: "Tine — Norway", category: "global_dairy", sector: "Government / Cooperative", location: "Oslo, Norway", specialties: ["Jarlsberg Cheese", "Norvegia", "Tine Milk"] },
  { id: 243, name: "Arla Foods Ingredients", category: "global_dairy", sector: "Government / Cooperative", location: "Aarhus, Denmark", specialties: ["Whey Protein Hydrolysates", "Alpha-lactalbumin"] },
  { id: 244, name: "FrieslandCampina Ingredients", category: "global_dairy", sector: "Government / Cooperative", location: "Wageningen, Netherlands", specialties: ["Galacto-oligosaccharides (GOS)", "Encapsulated Oils"] },
  { id: 245, name: "Sodiaal International", category: "global_dairy", sector: "Government / Cooperative", location: "Paris, France", specialties: ["Euroserum Whey Powder", "Nactalia"] },
  { id: 246, name: "Elle & Vire — France", category: "global_dairy", sector: "Private / MNC", location: "Condé-sur-Vire, France", specialties: ["Gourmet French Cream", "Elle & Vire Butter"] },
  { id: 247, name: "Groupe Lactalis International", category: "global_dairy", sector: "Private / MNC", location: "France", specialties: ["Global Cheese & Butter Operations"] },
  { id: 248, name: "FrieslandCampina Professional", category: "global_dairy", sector: "Government / Cooperative", location: "Netherlands", specialties: ["Foodservice Cream & Butter"] },
  { id: 249, name: "Hochland Group International", category: "global_dairy", sector: "Private / MNC", location: "Germany", specialties: ["Processed Cheese Plants in Europe"] },
  { id: 250, name: "DMK Group International", category: "global_dairy", sector: "Government / Cooperative", location: "Germany", specialties: ["Oldenburger Export Milk"] },

  // 251-350: Global Food, Beverage & Dairy Leaders (Global)
  { id: 251, name: "Kraft Heinz — USA", category: "fmcg_food", sector: "Private / MNC", location: "Chicago, USA", specialties: ["Kraft Singles Cheese", "Philadelphia Cream Cheese", "Heinz Ketchup"] },
  { id: 252, name: "Mondelez International — USA", category: "fmcg_food", sector: "Private / MNC", location: "Chicago, USA", specialties: ["Cadbury", "Milka", "Toblerone", "Philadelphia", "Oreo"] },
  { id: 253, name: "PepsiCo — USA", category: "fmcg_food", sector: "Private / MNC", location: "Purchase, NY, USA", specialties: ["Doritos", "Cheetos", "Sabra Hummus", "Gatorade", "Quaker"] },
  { id: 254, name: "General Mills — USA", category: "fmcg_food", sector: "Private / MNC", location: "Minneapolis, USA", specialties: ["Häagen-Dazs Ice Cream", "Yoplait Yogurt", "Cheerio Oats"] },
  { id: 255, name: "Kellogg's / Kellanova — USA", category: "fmcg_food", sector: "Private / MNC", location: "Battle Creek, USA", specialties: ["Corn Flakes", "Pringles", "Special K", "Pop-Tarts"] },
  { id: 256, name: "Mars — USA", category: "fmcg_food", sector: "Private / MNC", location: "McLean, Virginia, USA", specialties: ["Mars Bar", "Snickers", "M&M's", "Dove Chocolate", "Uncle Ben's"] },
  { id: 257, name: "The Hershey Company — USA", category: "fmcg_food", sector: "Private / MNC", location: "Hershey, Pennsylvania, USA", specialties: ["Hershey's Kisses", "Reese's", "Milk Chocolate"] },
  { id: 258, name: "Conagra Brands — USA", category: "fmcg_food", sector: "Private / MNC", location: "Chicago, USA", specialties: ["Reddi-wip Whipped Cream", "Hunt's", "Healthy Choice"] },
  { id: 259, name: "Tyson Foods — USA", category: "fmcg_food", sector: "Private / MNC", location: "Springdale, Arkansas, USA", specialties: ["Meat Processing", "Jimmy Dean", "Hillshire Farm"] },
  { id: 260, name: "JBS — Brazil", category: "fmcg_food", sector: "Private / MNC", location: "São Paulo, Brazil", specialties: ["World's Largest Meat Processor", "Primo Foods", "Seara"] },
  { id: 261, name: "Hormel Foods — USA", category: "fmcg_food", sector: "Private / MNC", location: "Austin, Minnesota, USA", specialties: ["SPAM", "Skippy Peanut Butter", "Applegate Organic"] },
  { id: 262, name: "Smithfield Foods — USA", category: "fmcg_food", sector: "Private / MNC", location: "Smithfield, Virginia, USA", specialties: ["Pork Processing & Bacon"] },
  { id: 263, name: "Perdue Farms — USA", category: "fmcg_food", sector: "Private / MNC", location: "Salisbury, Maryland, USA", specialties: ["Poultry & Organic Foods"] },
  { id: 264, name: "McCain Foods — Canada", category: "fmcg_food", sector: "Private / MNC", location: "Florenceville, Canada", specialties: ["McCain French Fries", "Frozen Potato Products"] },
  { id: 265, name: "Nomad Foods — UK", category: "fmcg_food", sector: "Private / MNC", location: "Middlesex, UK", specialties: ["Birds Eye", "Findus", "Iglo Frozen Foods"] },
  { id: 266, name: "Bunge — USA", category: "ingredients", sector: "Private / MNC", location: "St. Louis, USA", specialties: ["Oilseed Processing", "Plant Lipids for Food"] },
  { id: 267, name: "Cargill — USA", category: "ingredients", sector: "Private / MNC", location: "Minnetonka, Minnesota, USA", specialties: ["Global Food Ingredients & Grain Trading"] },
  { id: 268, name: "ADM — USA", category: "ingredients", sector: "Private / MNC", location: "Chicago, USA", specialties: ["Wild Flavors", "Nutrition & Specialty Proteins"] },
  { id: 269, name: "Olam Group — Singapore", category: "ingredients", sector: "Private / MNC", location: "Singapore", specialties: ["Cocoa, Coffee, Spices & Nuts Trading"] },
  { id: 270, name: "Kerry Group — Ireland", category: "ingredients", sector: "Private / MNC", location: "Tralee, Ireland", specialties: ["Global Taste & Nutrition Solutions"] },
  { id: 271, name: "Associated British Foods (ABF) — UK", category: "fmcg_food", sector: "Private / MNC", location: "London, UK", specialties: ["Twinings Tea", "Ovaltine", "AB Mauri Yeast"] },
  { id: 272, name: "Premier Foods — UK", category: "fmcg_food", sector: "Private / MNC", location: "St Albans, UK", specialties: ["Mr Kipling Cakes", "Bisto", "Ambrosia Custard"] },
  { id: 273, name: "Greggs — UK", category: "fmcg_food", sector: "Private / MNC", location: "Newcastle, UK", specialties: ["Greggs Bakery", "Sausage Rolls"] },
  { id: 274, name: "Dairy Crest (Saputo Dairy UK)", category: "global_dairy", sector: "Private / MNC", location: "Weybridge, UK", specialties: ["Cathedral City Cheddar", "Clover Spread"] },
  { id: 275, name: "Saputo Dairy UK — UK", category: "global_dairy", sector: "Private / MNC", location: "UK", specialties: ["Utterly Butterly", "Country Life Butter"] },
  { id: 276, name: "Yeo Valley Organic — UK", category: "global_dairy", sector: "Private / MNC", location: "Somerset, UK", specialties: ["Organic British Yogurt & Milk"] },
  { id: 277, name: "Meadow Foods — UK", category: "global_dairy", sector: "Private / MNC", location: "Chester, UK", specialties: ["Industrial Cream", "Butter & Milk Ingredients"] },
  { id: 278, name: "First Milk — UK", category: "global_dairy", sector: "Government / Cooperative", location: "Glasgow, UK", specialties: ["Lake District Cheddar", "Cooperative Milk"] },
  { id: 279, name: "Arla UK — UK", category: "global_dairy", sector: "Government / Cooperative", location: "Leeds, UK", specialties: ["Cravendale Pure Milk", "Arla Lactofree"] },
  { id: 280, name: "Müller UK & Ireland — UK", category: "global_dairy", sector: "Private / MNC", location: "Market Drayton, UK", specialties: ["Müllerlight Yogurt", "Müller Milk"] },
  { id: 281, name: "Ornua Foods — Ireland", category: "global_dairy", sector: "Government / Cooperative", location: "Leek, Staffordshire, UK", specialties: ["Kerrygold Butter Packing"] },
  { id: 282, name: "Kerry Group — Ireland", category: "ingredients", sector: "Private / MNC", location: "Tralee, Ireland", specialties: ["DaVinci Gourmet Syrups", "Dairy Flavors"] },
  { id: 283, name: "Glanbia Performance Nutrition — Ireland", category: "fmcg_food", sector: "Private / MNC", location: "Dublin, Ireland", specialties: ["ON Gold Standard Whey", "BSN", "SlimFast"] },
  { id: 284, name: "Valeo Foods — Ireland", category: "fmcg_food", sector: "Private / MNC", location: "Dublin, Ireland", specialties: ["Jacob's Biscuits", "Rowse Honey"] },
  { id: 285, name: "Dawn Meats — Ireland", category: "fmcg_food", sector: "Private / MNC", location: "Waterford, Ireland", specialties: ["Meat & Beef Processing"] },
  { id: 286, name: "Barry Callebaut — Switzerland", category: "ingredients", sector: "Private / MNC", location: "Zurich, Switzerland", specialties: ["World's Leading Cocoa & Chocolate Manufacturer"] },
  { id: 287, name: "Lindt & Sprüngli — Switzerland", category: "fmcg_food", sector: "Private / MNC", location: "Kilchberg, Switzerland", specialties: ["Lindt Chocolate Truffles", "Excellence Dark"] },
  { id: 288, name: "Nestlé Switzerland", category: "global_dairy", sector: "Private / MNC", location: "Vevey, Switzerland", specialties: ["Nestlé Global R&D & Operations"] },
  { id: 289, name: "Emmi — Switzerland", category: "global_dairy", sector: "Private / MNC", location: "Lucerne, Switzerland", specialties: ["Swiss Alpine Dairy Products"] },
  { id: 290, name: "Hero Group — Switzerland", category: "fmcg_food", sector: "Private / MNC", location: "Lenzburg, Switzerland", specialties: ["Hero Jams", "Beech-Nut Baby Food"] },
  { id: 291, name: "Meiji Co — Japan", category: "global_dairy", sector: "Private / MNC", location: "Tokyo, Japan", specialties: ["Meiji Milk", "Probiotic Yogurt PA-3"] },
  { id: 292, name: "Morinaga Milk — Japan", category: "global_dairy", sector: "Private / MNC", location: "Tokyo, Japan", specialties: ["Morinaga Aloe Yogurt", "Mount Rainier Coffee"] },
  { id: 293, name: "Megmilk Snow Brand — Japan", category: "global_dairy", sector: "Private / MNC", location: "Tokyo, Japan", specialties: ["Snow Brand Cheese & Milk"] },
  { id: 294, name: "Yakult Honsha — Japan", category: "global_dairy", sector: "Private / MNC", location: "Tokyo, Japan", specialties: ["Yakult Probiotic Fermented Milk (L. casei Shirota)"] },
  { id: 295, name: "Ezaki Glico — Japan", category: "fmcg_food", sector: "Private / MNC", location: "Osaka, Japan", specialties: ["Pocky", "Glico Almond Milk", "Papico Ice Cream"] },
  { id: 296, name: "Lotte Corporation — South Korea / Japan", category: "fmcg_food", sector: "Private / MNC", location: "Seoul, South Korea", specialties: ["Lotte Choco Pie", "Lotte Havmor Ice Cream"] },
  { id: 297, name: "Seoul Dairy Cooperative — South Korea", category: "global_dairy", sector: "Government / Cooperative", location: "Seoul, South Korea", specialties: ["Seoul Milk #1 Dairy in Korea"] },
  { id: 298, name: "Maeil Dairies — South Korea", category: "global_dairy", sector: "Private / MNC", location: "Seoul, South Korea", specialties: ["Maeil Organic Milk", "Amazing Oat Milk"] },
  { id: 299, name: "Namyang Dairy Products — South Korea", category: "global_dairy", sector: "Private / MNC", location: "Seoul, South Korea", specialties: ["French Cafe Coffee", "GT Milk"] },
  { id: 300, name: "Yili Group — China", category: "global_dairy", sector: "Private / MNC", location: "Hohhot, China", specialties: ["Satine Organic Milk", "Ambrosial Greek Yogurt"] },
  { id: 301, name: "Mengniu Dairy — China", category: "global_dairy", sector: "Private / MNC", location: "Hohhot, China", specialties: ["Milk Deluxe", "Suanyan Fermented Milk"] },
  { id: 302, name: "Bright Dairy & Food — China", category: "global_dairy", sector: "Private / MNC", location: "Shanghai, China", specialties: ["Momchilovtsi Bulgarian Yogurt", "Bright Fresh Milk"] },
  { id: 303, name: "Junlebao Dairy — China", category: "global_dairy", sector: "Private / MNC", location: "Shijiazhuang, China", specialties: ["Junlebao Infant Formula", "Zero Sugar Yogurt"] },
  { id: 304, name: "Hangzhou Wahaha Group — China", category: "fmcg_food", sector: "Private / MNC", location: "Hangzhou, China", specialties: ["Wahaha AD Calcium Milk", "Nutrient Drinks"] },
  { id: 305, name: "Want Want China Holdings — China", category: "fmcg_food", sector: "Private / MNC", location: "Shanghai, China", specialties: ["Want Want Milk", "Rice Crackers"] },
  { id: 306, name: "Inner Mongolia Yili Industrial Group", category: "global_dairy", sector: "Private / MNC", location: "China", specialties: ["Global Top 5 Dairy Group"] },
  { id: 307, name: "China Modern Dairy Holdings — China", category: "global_dairy", sector: "Private / MNC", location: "Anhui, China", specialties: ["Large Scale Mega Dairy Farming"] },
  { id: 308, name: "Bongrain Asia / Savencia", category: "global_dairy", sector: "Private / MNC", location: "Singapore", specialties: ["Foodservice Butter & Cheese"] },
  { id: 309, name: "Fonterra Australia", category: "global_dairy", sector: "Government / Cooperative", location: "Melbourne, Australia", specialties: ["Western Star Butter", "Perfect Italiano Cheese"] },
  { id: 310, name: "Bega Cheese — Australia", category: "global_dairy", sector: "Private / MNC", location: "Bega, New South Wales", specialties: ["Bega Peanut Butter", "Bega Cheese Slices"] },
  { id: 311, name: "Saputo Dairy Australia", category: "global_dairy", sector: "Private / MNC", location: "Melbourne, Australia", specialties: ["Devondale Milk", "Sungold Milk", "Cheer Cheese"] },
  { id: 312, name: "Murray Goulburn / Saputo", category: "global_dairy", sector: "Private / MNC", location: "Victoria, Australia", specialties: ["Devondale SMP & Butter"] },
  { id: 313, name: "Norco Cooperative — Australia", category: "global_dairy", sector: "Government / Cooperative", location: "Lismore, NSW, Australia", specialties: ["Norco 100% Australian Farmer Milk"] },
  { id: 314, name: "Lactalis Australia (Parmalat)", category: "global_dairy", sector: "Private / MNC", location: "Brisbane, Australia", specialties: ["Pauls Milk", "Vaalia Yogurt", "Ice Break Iced Coffee"] },
  { id: 315, name: "Lion Dairy & Drinks (Bega)", category: "global_dairy", sector: "Private / MNC", location: "Docklands, Australia", specialties: ["Dare Iced Coffee", "Farmers Union Yogurt"] },
  { id: 316, name: "Devondale Murray Goulburn", category: "global_dairy", sector: "Private / MNC", location: "Australia", specialties: ["UHT Milk & Butter"] },
  { id: 317, name: "Goodman Fielder — Australia", category: "fmcg_food", sector: "Private / MNC", location: "Sydney, Australia", specialties: ["Meadow Lea Margarine", "Helga's Bread"] },
  { id: 318, name: "Freedom Foods Group (noumi)", category: "fmcg_food", sector: "Private / MNC", location: "Sydney, Australia", specialties: ["MILKLAB Oat & Almond Milk", "Australia's Own"] },
  { id: 319, name: "A2 Milk Company — New Zealand", category: "global_dairy", sector: "Private / MNC", location: "Auckland, New Zealand", specialties: ["a2 Platinum Infant Formula", "A2 Protein Milk"] },
  { id: 320, name: "Synlait Milk — New Zealand", category: "global_dairy", sector: "Private / MNC", location: "Dunsandel, New Zealand", specialties: ["Aseptic Beverage & Infant Powder"] },
  { id: 321, name: "Dairy Farmers of America (DFA)", category: "global_dairy", sector: "Government / Cooperative", location: "USA", specialties: ["5000+ US Family Farm Milk"] },
  { id: 322, name: "Land O'Lakes — USA", category: "global_dairy", sector: "Government / Cooperative", location: "Arden Hills, Minnesota", specialties: ["Land O'Lakes Butter", "Deli Cheese"] },
  { id: 323, name: "Schreiber Foods USA", category: "global_dairy", sector: "Private / MNC", location: "Green Bay, Wisconsin", specialties: ["Process Cheese & Cream Cheese"] },
  { id: 324, name: "Hilmar Cheese Company — USA", category: "global_dairy", sector: "Private / MNC", location: "Hilmar, California", specialties: ["Cheddar Cheese Block", "Whey Protein Isolate WPI"] },
  { id: 325, name: "Tillamook County Creamery Association — USA", category: "global_dairy", sector: "Government / Cooperative", location: "Tillamook, Oregon", specialties: ["Tillamook Aged Cheddar", "Tillamook Ice Cream"] },
  { id: 326, name: "Organic Valley (CROPP Cooperative) — USA", category: "global_dairy", sector: "Government / Cooperative", location: "La Farge, Wisconsin", specialties: ["Organic Grass-Fed Milk", "Pasture Butter"] },
  { id: 327, name: "Cabot Creamery (Agri-Mark) — USA", category: "global_dairy", sector: "Government / Cooperative", location: "Waitfield, Vermont", specialties: ["Cabot Sharp Cheddar", "Greek Yogurt"] },
  { id: 328, name: "Prairie Farms Dairy — USA", category: "global_dairy", sector: "Government / Cooperative", location: "Edwardsville, Illinois", specialties: ["Prairie Farms Milk", "Dip", "Ice Cream"] },
  { id: 329, name: "Foremost Farms USA", category: "global_dairy", sector: "Government / Cooperative", location: "Middleton, Wisconsin", specialties: ["Mozzarella", "Provolone", "Whey Powder"] },
  { id: 330, name: "California Dairies Inc (CDI) — USA", category: "global_dairy", sector: "Government / Cooperative", location: "Visalia, California", specialties: ["Challenge Butter", "Nonfat Dry Milk Powder"] },
  { id: 331, name: "Darigold — USA", category: "global_dairy", sector: "Government / Cooperative", location: "Seattle, Washington", specialties: ["Darigold FIT High Protein Milk", "Ultra-Filtered Milk"] },
  { id: 332, name: "Shamrock Foods — USA", category: "global_dairy", sector: "Private / MNC", location: "Phoenix, Arizona", specialties: ["Shamrock Farms Milk", "Rockin' Refuel"] },
  { id: 333, name: "HP Hood — USA", category: "global_dairy", sector: "Private / MNC", location: "Lynnfield, Massachusetts", specialties: ["Lactaid Milk", "Planet Oat Oatmilk", "Hood Cream"] },
  { id: 334, name: "Dean Foods (DFA) — USA", category: "global_dairy", sector: "Private / MNC", location: "Dallas, Texas", specialties: ["Dairypure Milk", "TruMoo Chocolate Milk"] },
  { id: 335, name: "Borden Dairy — USA", category: "global_dairy", sector: "Private / MNC", location: "Dallas, Texas", specialties: ["Elsie the Cow", "Borden Whole Milk", "Dutch Chocolate"] },
  { id: 336, name: "Mayfield Dairy Farms — USA", category: "global_dairy", sector: "Private / MNC", location: "Athens, Tennessee", specialties: ["Mayfield Ice Cream", "Yellow Jug Milk"] },
  { id: 337, name: "Blue Bell Creameries — USA", category: "ice_cream", sector: "Private / MNC", location: "Brenham, Texas", specialties: ["Blue Bell Homemade Vanilla", "Dutch Chocolate"] },
  { id: 338, name: "Turkey Hill Dairy — USA", category: "ice_cream", sector: "Private / MNC", location: "Conestoga, Pennsylvania", specialties: ["Turkey Hill All Natural Ice Cream", "Iced Tea"] },
  { id: 339, name: "Anderson Erickson Dairy (AE Dairy) — USA", category: "global_dairy", sector: "Private / MNC", location: "Des Moines, Iowa", specialties: ["AE Whole Milk", "AE Cottage Cheese"] },
  { id: 340, name: "Kemps (DFA) — USA", category: "global_dairy", sector: "Government / Cooperative", location: "St. Paul, Minnesota", specialties: ["Kemps Frozen Yogurt", "Kemps Milk"] },
  { id: 341, name: "Crystal Creamery — USA", category: "global_dairy", sector: "Private / MNC", location: "Modesto, California", specialties: ["Crystal Pure Milk", "Butter", "Sour Cream"] },
  { id: 342, name: "Clover Sonoma — USA", category: "global_dairy", sector: "Private / MNC", location: "Petaluma, California", specialties: ["Clover Organic Milk", "Non-GMO Dairy"] },
  { id: 343, name: "Challenge Dairy Products — USA", category: "global_dairy", sector: "Government / Cooperative", location: "Dublin, California", specialties: ["Challenge Butter", "Spreadable Butter"] },
  { id: 344, name: "Sargento Foods — USA", category: "global_dairy", sector: "Private / MNC", location: "Plymouth, Wisconsin", specialties: ["Sargento Shredded Cheese", "Balanced Breaks"] },
  { id: 345, name: "Grande Cheese Company — USA", category: "global_dairy", sector: "Private / MNC", location: "Fond du Lac, Wisconsin", specialties: ["Authentic Italian Pizzeria Mozzarella"] },
  { id: 346, name: "Associated Milk Producers Inc (AMPI) — USA", category: "global_dairy", sector: "Government / Cooperative", location: "New Ulm, Minnesota", specialties: ["Dinner Bell Butter", "Process Cheese"] },
  { id: 347, name: "Foremost Farms Ingredients — USA", category: "ingredients", sector: "Government / Cooperative", location: "Wisconsin", specialties: ["Demineralized Whey 90%", "WPC80"] },
  { id: 348, name: "Hilmar Ingredients — USA", category: "ingredients", sector: "Private / MNC", location: "Hilmar, California", specialties: ["Whey Protein Hydrolysate", "Lactose 200 Mesh"] },
  { id: 349, name: "Leprino Foods — USA", category: "global_dairy", sector: "Private / MNC", location: "Denver, Colorado", specialties: ["World's Largest Mozzarella Cheese Producer", "Whey Protein"] },
  { id: 350, name: "Agropur USA", category: "global_dairy", sector: "Government / Cooperative", location: "Appleton, Wisconsin", specialties: ["Custom Contract Cheese & Whey Drying"] },
];
