import { Inter, Space_Grotesk, Noto_Sans_Devanagari } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { AuthProvider } from '@/context/auth-context';
import { Toaster } from '@/components/ui/toaster';
import { SubscriptionProvider } from '@/context/subscription-context';
import { LanguageProvider } from '@/context/language-context';
import Script from 'next/script'; // यह पहले से import है
import { FirebaseClientProvider } from '@/firebase/client-provider';
import { SplashScreenProvider } from '@/context/splash-screen-context';
import { ReadingModeProvider } from '@/context/reading-mode-context';

// ===== यह रहा आपका सही फ़ॉन्ट कोड =====
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
});

const notoDevanagari = Noto_Sans_Devanagari({
  subsets: ['latin'],
  variable: '--font-noto-devanagari',
  weight: ['400', '700'],
});
// =====================================


// ===== 1. AdSense Meta Tag (यह सही है) =====
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    'google-adsense-account': 'ca-pub-1786473188592937',
  },
};
// =============================================

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ===== 2. AdSense Script (यह सही है) ===== */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1786473188592937"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
        {/* ================================================== */}
      </head>

      <body className={cn('font-body antialiased', inter.variable, spaceGrotesk.variable, notoDevanagari.variable)}>
        {/* ... (आपका बाकी का Body कोड) ... */}
        <SplashScreenProvider>
          <ReadingModeProvider>
            <FirebaseClientProvider>
              <LanguageProvider>
                <SubscriptionProvider>
                  <AuthProvider>
                    {children}
                  </AuthProvider>
                </SubscriptionProvider>
              </LanguageProvider>
            </FirebaseClientProvider>
          </ReadingModeProvider>
        </SplashScreenProvider>
        <Toaster />
        <Script id="chunk-error-handler">
          {`
            window.addEventListener('error', (event) => {
              if (event.message && (event.message.includes('ChunkLoadError') || event.message.includes('Loading chunk'))) {
                console.warn('ChunkLoadError detected, forcing page reload.');
                window.location.reload();
              }
            });
          `}
        </Script>
      </body>
    </html>
  );
}
