import { Inter, Space_Grotesk, Noto_Sans_Devanagari } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { AuthProvider } from '@/context/auth-context';
import { Toaster } from '@/components/ui/toaster';
import { SubscriptionProvider } from '@/context/subscription-context';
import { LanguageProvider } from '@/context/language-context';
import Script from 'next/script';
import { FirebaseClientProvider } from '@/firebase/client-provider';
import { SplashScreenProvider } from '@/context/splash-screen-context';
import { ReadingModeProvider } from '@/context/reading-mode-context';


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
});

const notoDevanagari = Noto_Sans_Devanagari({
  subsets: ['latin'],
  variable: '--font-noto-devanagari',
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('font-body antialiased', inter.variable, spaceGrotesk.variable, notoDevanagari.variable)}>
        <SplashScreenProvider>
        <ReadingModeProvider>
          <FirebaseClientProvider>
            <LanguageProvider>
              <SubscriptionProvider>
                <AuthProvider>
                  {children}
                </AuthProvider>
              </SubscriptionProvider>
            </LanguageProvider>
          </FirebaseClientProvider>
        </ReadingModeProvider>
        </SplashScreenProvider>
        <Toaster />
        <Script id="chunk-error-handler">
          {`
            window.addEventListener('error', (event) => {
              if (event.message && (event.message.includes('ChunkLoadError') || event.message.includes('Loading chunk'))) {
                console.warn('ChunkLoadError detected, forcing page reload.');
                window.location.reload();
              }
            });
          `}
        </Script>
      </body>
    </html>
  );
}
